[[commentary]]
quote='''
And lastly, her son Barak shows the chief part of the victory was in the hands of a woman when he said, “If you will not go with me I will not go, because I do not know on what day the Lord will send his angel with me.” How great, then, was the might of that woman to whom the leader of the army says, “If you will not go I will not go.” How great, I say, the fortitude of the widow who does not protect her son from dangers through motherly affection but rather with the zeal of a mother exhorts her son to go forth to victory, while saying that the decisive point of that victory is in the hand of a woman!
'''
source_url='https://historicalchristian.faith/by_father.php?file=Ambrose%2520of%2520Milan%2FConcerning%2520Widows.html'
source_title="Concerning Widows 8.43-46"
