[[commentary]]
quote='''
The end of the war was also the end of their wrath, and anger turned to sorrow. Then, putting off their armor, the men of Israel met together and wept much and celebrated a fast, grieving that one tribe of their brothers had perished and a strong band of people had been wiped out.
'''
source_url=''
source_title="LETTER 33"
