[[commentary]]
quote='''
But if Christ also is a prophet, how is this man greater than all. But it is said, among those born of woman, not of a virgin. For He was greater than those, whose equal he might be in way of birth, as it follows, For I say unto you, of those that are born of woman, there is not a greater prophet than John the Baptist.

Lastly, so impossible is it that there should be any comparison between John and the Son of God, that he is counted even below the angels; as it follows, But he that is least in the kingdom of God, is greater than he.

For He is of another nature, which bears not comparison with human kind. For there can be no comparing of God with men.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%25207.html'
source_title='Catena Aurea by Aquinas'

[[commentary]]
quote='''
But is not even He greater, of whom Moses said: 'The Lord thy God will raise up unto thee a Prophet' (Deut. xviii, 15)? And of whom it is said: 'And every soul which will not hear that Prophet shall be destroyed from the people' (ibid., 19)? If, then, Christ is a prophet, how is He greater than all? Do we deny that Christ is a prophet? Nay, we confess Him to be the Lord of the prophets. But I assert that John is a prophet, and I say that he is greater than all, but only among them that are born of women, not among those that are born of a virgin. For indeed he was greater than those with whom he could be equal by the lot of birth. That nature is different from this, and cannot be compared with human generations. There can be no comparison between man and God; each person is preferred to their own. In fact, to such an extent could there be no comparison between John and the Son of God; that he is even considered inferior to the angels.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Ambrose%2520of%2520Milan%2FCommentary%2520on%2520Luke.html'
source_title="Commentary on Luke"
