[[commentary]]
quote='''
He would not have said that all the temptation was ended, had there not been in the three temptations which have been described the materials for every crime; for the causes of temptations are the causes of desire, namely, the delight of the flesh, the pomp of vain-glory, greediness of power.

You see then that the devil is not obstinate on the field, is wont to give way to true virtue; and if he ceases not to hate, he yet dreads to advance, for so he escapes a more frequent defeat. As soon then as he heard the name of God, he retired (it is said) for a season, for afterwards he comes not to tempt, but to fight openly.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%25204.html'
source_title='Catena Aurea by Aquinas'
