[[commentary]]
quote='''
They behold him rising up, still disbelieving, and marvel at his departing; as it follows, And they were all amazed.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%25205.html'
source_title='Catena Aurea by Aquinas'


[[commentary]]
quote='''
But they had rather fear the miracles of divine working, than believe them. As it follows, And they were filled with fear. But if they had believed they had not surely feared, but loved; for perfect love casteth out fear. But this was no careless or trifling cure of the paralytic, since our Lord is said to have prayed first, not for the petition's sake, but for an example.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%25205.html'
source_title='Catena Aurea by Aquinas'
