[[commentary]]
quote='''
Neither indignation at their treatment, nor displeasure at their wickedness, caused our Lord to abandon Judæa, but unmindful of His injuries, and remembering mercy, at one time by teaching, at another by healing, He softens the hearts of this unbelieving people, as it is said, And he went down to Capernaum.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%25204.html'
source_title='Catena Aurea by Aquinas'


[[commentary]]
quote='''
The work of divine healing commenced on the sabbath, signifying thereby that he began anew where the old creation ceased, in order that He might declare at the very beginning that the Son of God was not under the Law, but above the Law. Rightly also He began on the sabbath, that He might show Himself the Creator, who interweaves His works one within another, and follows up that which He had before begun; just as a builder determining to reconstruct a house, begins to pull down the old one, not from the foundation, but from the top, so as to apply his hand first to that part, where he had before left off. Holy men may through the word of God deliver from evil spirits, but to bid the dead rise again, is the work of Divine power alone.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%25204.html'
source_title='Catena Aurea by Aquinas'


[[commentary]]
quote='''
He describes the works of divine healing begun on the sabbath day, to show from the outset that the new creation began where the old creation ceased. He showed us that the Son of God is not under the law but above the law, and that the law will not be destroyed but fulfilled. For the world was not made through the law but by the Word, as we read: “By the Word of the Lord were the heavens established.” Thus the law is not destroyed but fulfilled, so that the renewal of humankind, already in error, may occur. The apostle too says, “Stripping yourselves of the old man, put on the new, who was created according to Christ.” He fittingly began on the sabbath, that he may show himself as Creator. He completed the work that he had already begun by weaving together works with works.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Ambrose%2520of%2520Milan%2FCommentary%2520on%2520Luke.html'
source_title="Commentary on Luke"
