[[commentary]]
quote='''
It is fitting that it be recorded that the first Adam was cast out of Paradise into the desert, that you may observe how the second Adam returned from the desert to Paradise.… Adam brought death through the tree. Christ brought life through the cross. Adam, naked of spiritual things, covered himself with the foliage of a tree. Christ, naked of worldly things, did not desire the trappings of the body. Adam lived in the desert. Christ lived in the desert, for he knew where he could find the lost. With their error canceled, he could recall them to Paradise.…So Jesus, full of the Holy Spirit, is led into the desert for a purpose, in order to challenge the devil. If he had not fought, he would not have conquered him for me.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Ambrose%2520of%2520Milan%2FCommentary%2520on%2520Luke.html'
source_title="EXPOSITION OF THE GOSPEL OF LUKE 4.7, 14"

[[commentary]]
quote='''
He was led therefore into the wilderness, to the intent that He might provoke the devil, for if the one had not contended, the other it seems had not conquered. In a mystery, it was to deliver that Adam from exile who was cast out of Paradise into the wilderness. By way of example, it was to show us that the devil envies us, whenever we strive after better things; and that then we must use caution, lest the weakness of our minds should lose us the grace of the mystery. Hence it follows: And he was tempted of the devil.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%25204.html'
source_title='Catena Aurea by Aquinas'

[[commentary]]
quote='''
There are three things which united together conduce to the salvation of man; The Sacrament, The Wilderness, Fasting. No one who has not rightly contended receives a crown, but no one is admitted to the contest of virtue, except first being washed from the stains of all his sins, he is consecrated with the gift of heavenly grace.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%25204.html'
source_title='Catena Aurea by Aquinas'
