[[commentary]]
quote='''
After instructing him in the knowledge of the faith, He adds, Thou knowest the commandments. As though He said, Know God first, and then will it be time to seek what thou askest.

But you may observe that these commandments consist in not doing certain things; that if thou hast not committed adultery, thou art chaste; if thou stealest not, honestly disposed; if thou bearest not false witness, truth-telling. Virtue then we see is rendered easy through the goodness of the Lawgiver. For He speaks of avoiding of evil, not practising of good. And any cessation from action is easier than any actual work.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%252018.html'
source_title='Catena Aurea by Aquinas'
