[[commentary]]
quote='''
If (Noah) had not had this (conservative power) by so short a route, there would (still) be this (consideration) to warrant our assertion of (the genuineness of) this Scripture: he could equally have renewed it, under the Spirit's inspiration, after it had been destroyed by the violence of the deluge, as, after the destruction of Jerusalem by the Babylonian storming of it, every document of the Jewish literature is generally agreed to have been restored through Ezra.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520the%2520Apparel%2520of%2520Women%2FBook%25201.html"
source_title="On the Apparel of Women Book I"
