[[commentary]]
quote='''
Likewise, Third Kings, chapter eight: If heaven and the heavens of heavens cannot contain you, how much more this house which I have built? If therefore the being of God can be contained by nothing and circumscribed by nothing, it must be acknowledged that it has entirely the character of the infinite.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FQuaestiones%2520Disputatae%2FDe%2520Mysterio%2520Trinitatis%2FQuestion%25204.html'
source_title='Quaestiones Disputatae, De Mysterio Trinitatis, Question 4'
