[[commentary]]
quote='''
The blessed Virgin on account of her sanctity, piety, and sublimity had a crown of precious stone. Who is this stone? Certainly Christ. Whence blessed Peter: "Behold, I shall place in the foundation a precious stone." The blessed Virgin was crowned with this stone in the flesh: seeing in the flesh the glorified body of Christ, seeing in spirit his glorified soul, and in mind his Divinity. Christ was crowned first, and she afterward.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollationes%2520de%2520Septem%2520Donis%2FCollation%25206.html'
source_title='Collationes de Septem Donis, Collation 6'

[[commentary]]
quote='''
Christ is the foundation of this faith. For He is the cornerstone of which Isaiah and Peter speak: See, I am laying a stone in Sion, a stone that has been tested, a precious cornerstone as a sure foundation. And the Apostle: You are built upon the foundation of the apostles and prophets with Christ Jesus Himself as the chief cornerstone.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollations%2520on%2520the%2520Hexaemeron%2FCollation%25209.html'
source_title='Collations on the Hexaemeron, Collation 9'
