[[commentary]]
quote='''
Another particle of the perfection of the fear of the Lord consists in perfect promptitude of obedience. Hence in the book of Chronicles: "Let the fear of the Lord be with you, and do all things with diligence": as if to say: do not be sluggish or negligent, because it is written in Ecclesiastes: "He who fears God neglects nothing." If I believed that a thief was going to enter my chamber and carry off my treasure, I would not leave the window open. You must always fear God, because he who "keeps the whole law but offends in one point has become guilty of all."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollationes%2520de%2520Septem%2520Donis%2FCollation%25202.html'
source_title="Collationes de Septem Donis, Collation 2"
