[[commentary]]
quote='''
"What does it profit a man of all his labor," in body, "and affliction of spirit," in mind, "by which he is tormented under the sun?" As if to say: nothing; whence Proverbs 23: "Labor not to become rich, but set bounds to your prudence." It does not profit, namely him who labors for the sake of possessing these visible things. Whence Bernard says: "With others are the fruits of riches, but to the rich fall only the name and the solicitude"; and therefore it does not profit; whence below in chapter 5: "What does it profit the possessor, except that he beholds riches with his eyes?"
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520Ecclesiastes%2FChapter%25202.html'
source_title='Commentary on Ecclesiastes, Chapter 2'

[[commentary]]
quote='''
The world is vain also because it does not give rest to the one who labors, and therefore he who labors for worldly things labors in vain: Ecclesiastes 2: What does it profit a man from all his labor, by which he labors under the sun? All his days are full of labors and sorrows, nor does his mind rest at night: and is this not vanity? because he labors in vain, because he does not rest. This world cannot give rest, because it itself does not endure, but rather always revolves: therefore those who cling to it must needs go around in circles. Therefore it is said in the Psalm: The wicked walk round about.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520Ecclesiastes%2FProoemium.html'
source_title='Commentary on Ecclesiastes, Prooemium'
