[[commentary]]
quote='''
"These, I say, perish in the worst affliction," because it is necessary that he relinquish them with sorrow: Job twenty-seven: "The rich man, when he shall sleep, shall take nothing with him." Nor are they only left behind by their owner, but they are also lost by the son, whence he adds: "He has begotten a son, who shall be in the utmost destitution." There is an utmost destitution, and this is of all goods, concerning which Proverbs six: "Want shall come upon you like a traveler" etc.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520Ecclesiastes%2FChapter%25205.html'
source_title="Commentary on Ecclesiastes, Chapter 5"
