[[commentary]]
quote='''
The promise of a bodily posterity was made to Abraham, for it is written: "So shall your posterity be." The promise of a spiritual posterity was also made to him, for through faith he was to be the father of a multitude. The flesh of Abraham gave forth offspring and was thus multiplied. All the more so would his spiritual begetting be fruitful: for he begot spiritually through his fruitful mind. Now, the great number of thoughts arising out of faith transcend in clarity the light of the stars.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollations%2520on%2520the%2520Hexaemeron%2FCollation%252010.html'
source_title='Collations on the Hexaemeron, Collation 10'

[[commentary]]
quote='''
Conjugal chastity accords with the written law by reason of the divine promise: because the Lord promised to Abraham, Genesis 17: You shall be the father of many nations; and I will make you increase most exceedingly, and I will establish you among nations, and kings shall come forth from you. Since therefore the Lord as a benefit promised that He would give offspring to Abraham through the way of marriage, it is evident that conjugal chastity accords with the written law.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FQuaestiones%2520Disputatae%2FDe%2520Perfectione%2520Evangelica%2FQuestion%25203.html'
source_title='Disputed Questions on Evangelical Perfection, Question 3'
