[[commentary]]
quote='''
Likewise, on that passage of James: Has not God chosen the poor; the Gloss says: "He chose poor parents, by whose service He would be raised"; but the destitution of Christ's parents was very great, according to that passage of Luke 2: She wrapped Him in swaddling clothes and laid Him in a manger: therefore Christ loved poverty not only in Himself, but also in others.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FQuaestiones%2520Disputatae%2FDe%2520Perfectione%2520Evangelica%2FQuestion%25202.html'
source_title='Disputed Questions on Evangelical Perfection, Question 2'
