[[commentary]]
quote='''
"And they returned," because they could not avoid reproof and also could not carry out their evil design. Therefore he says: "And they returned, each one to his own house," so that not one remained with another; whence Sirach 21: "The congregation of sinners is like gathered tow, and their end is a flame of fire"; Psalm: "Scatter the nations that desire wars."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520John%2FChapter%25207.html'
source_title='Commentary on John, Chapter 7'
