[[commentary]]
quote='''
"Therefore they wished to receive him into the ship," recognizing him and rejoicing in safety: "and immediately the ship was at the land to which they were going," that is, to which — because the almighty Lord was there, who was not carried by the ship but carried it: Hebrews 1: "Upholding all things by the word of his power"; and "immediately," because Wisdom 12: "For the power to act is subject to you whenever you will." Whence there was a threefold miracle, namely the walking upon the sea, the calming of the storm, and the most swift arrival at port.

Spiritually, it should be noted what the village is to which they go, how they cross over, and by what guide they arrive. The village to which they go is Capernaum, which is interpreted as "the most beautiful village." This is the heavenly homeland, in which there is supreme beauty, as is said of the Saints in Wisdom 5: "They shall receive the kingdom of beauty and the diadem of comeliness from the hand of the Lord."

To this village one crosses through the sea, that is, through the bitternesses of tribulations: Acts 14: "Through many tribulations we must enter the kingdom of God."

Through this sea carries the little ship of penance, in which man is saved, according to that passage in Acts 27: "Unless you remain in the ship, you cannot be saved"; likewise: "If we do not do penance, we shall fall into the hands of the Lord," Sirach 2.

This little ship is shaken when it is battered by the blasts of temptations: Matthew 7: "The floods came, and the winds blew."

Those sailing see the Lord walking, as here; those fighting see him standing, Acts 7; those contemplating, sitting, Isaiah 6: "I saw the Lord sitting."

But the Lord is present and leads to port, according to that passage in Isaiah 43: "When you pass through the waters, I will be with you, and the rivers shall not overwhelm you"; and according to that passage of the Psalm: "I am with him in tribulation; I will deliver him and glorify him; with length of days I will fill him and show him my salvation."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520John%2FChapter%25206.html'
source_title='Commentary on John, Chapter 6'
