[[commentary]]
quote='''
Here the descent of the disciples to depart is touched upon; for the Lord wished to dismiss the crowds secretly, so that they would not find him: therefore he sent his disciples ahead, so that descending from the mountain they might cross over. For this reason he says: "But when evening had come" — this is the hour of returning to lodging — "his disciples had descended to the sea," namely, so that they might cross over.

It is asked concerning the descent of the disciples: because it is said that they went down when evening had come, how did they leave their Master alone? It seems that they were blameworthy. Likewise it is said that the disciples came to Capernaum, because in Mark 6 it is said that he commanded them to come to Bethsaida.

It must be said that, as Matthew says, the Lord compelled his disciples to get into the boat: therefore they were not blameworthy, because they obeyed the Lord. To what is objected concerning the contradiction, it must be said that Mark names the nearest town, but John names the one to which they intended to go.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520John%2FChapter%25206.html'
source_title='Commentary on John, Chapter 6'
