[[commentary]]
quote='''
"They therefore said to him: Who are you?" Still they press on and state the reason for their insistence: "That we may give an answer to those who sent us. What do you say about yourself?" It seemed foolish to them to return to those who sent them without a definite answer. For it is the mark of a wise messenger to bring back definite answers; Proverbs 22: "Behold, I have written down wisdom for you, so that you might answer with words of truth to those who sent you."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520John%2FChapter%25201.html'
source_title='Commentary on John, Chapter 1'
