[[commentary]]
quote='''
And because this seems unreasonable and incredible, that he should give to one who has abundance, therefore it is added: And they said to him: Lord, he has ten minas, as if they were saying: this does not seem to be a right judgment.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520Luke%2FChapter%252019.html'
source_title='Commentary on Luke, Chapter 19'
