[[commentary]]
quote='''
Thirdly, with regard to the motivating reason, he adds: For the Son of Man came to seek, through wisdom; the Psalm: "I have gone astray like a sheep that was lost; seek your servant, O Lord," etc.

And to save what had perished, namely through mercy: the last chapter of Second Paralipomenon: "Unworthy as I am, you will save me according to your great mercy"; and this is saving mercy. On account of which He is also called Jesus: Matthew one: "You shall call His name Jesus: for He shall save His people from their sins"; and Acts four: "Neither is there salvation in any other. For there is no other name under heaven given to men, by which we must be saved." Hence Romans ten: "Everyone, whosoever shall call upon the name of the Lord, shall be saved."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520Luke%2FChapter%252019.html'
source_title='Commentary on Luke, Chapter 19'
