[[commentary]]
quote='''
Third, as regards the deceitfulness of the Pharisees in evading, it is added: But they thought within themselves, saying: If we shall say: From heaven, confessing the truth, he will say to us: Why then did you not believe him? thereby reproaching our unbelief, by which they refused to believe a heavenly man, according to that passage of Matthew 11: "John came neither eating nor drinking, and they say: He has a demon."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520Luke%2FChapter%252020.html'
source_title='Commentary on Luke, Chapter 20'
