[[commentary]]
quote='''
And he said: I ask you therefore, father, etc. After the denial of mercy with respect to one's own person, here is added the denial with respect to a related person. Concerning which four things are introduced, namely the petition for mercy with respect to a related person, the denial of the mercy requested, the reason for the petition proposed, and the approval of the response already given.

First, therefore, as regards the petition for mercy with respect to a related person, he says: And he said: I ask you therefore, father, that you send him to my father's house. Now this petition was carnal, because it extended only to his brothers.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520Luke%2FChapter%252016.html'
source_title='Commentary on Luke, Chapter 16'
