[[commentary]]
quote='''
In the allegorical sense, the sun signifies Christ. "The sun rises and the sun goes down." It rises in the nativity, it goes down in death; it orbits through noon in the ascension; it is inclined to the north in the judgment. Malachias refers to the first: "But for you who fear My name, there will arise the Sun of Justice with its healing rays."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollations%2520on%2520the%2520Hexaemeron%2FCollation%252013.html'
source_title='Collations on the Hexaemeron, Collation 13'
