[[commentary]]
quote='''
A figure preceded in the rod and flower of Aaron. The history is in the rod of Aaron, which, cut off and dry, in the space of a single night put forth leaves, flowered, and brought forth fruit. Who brought it about that the Virgin conceived? Certainly the Holy Spirit, who is a love fervent, fruitful, undefiled, virile, incorrupt, and deifying. That he is a fruitful love is signified in the rod of Aaron, which in the space of a night put forth leaves, flowered, and brought forth fruit.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollationes%2520de%2520Septem%2520Donis%2FCollation%25206.html'
source_title='Collationes de Septem Donis, Collation 6'
