[[commentary]]
quote='''
Just as by following the glorious Virgin we become precious and holy, so by following Eve we become wicked and worthless. Whence in Proverbs: "The price of a harlot is scarcely one loaf of bread; but a woman captures the precious soul of a man." O foolish Eve, for the eating of one fruit you sold yourself and your husband and all of us! O son of Eve! Beware, lest you be an imitator of Eve; but for whatever pleasure you give your soul, you are an imitator of Eve.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollationes%2520de%2520Septem%2520Donis%2FCollation%25206.html'
source_title='Collationes de Septem Donis, Collation 6'
