[[commentary]]
quote='''
The Holy Spirit here describes the gift of counsel with respect to the preliminary act, and this with respect to the intrinsic act and the extrinsic act, and with respect to the proper act. The first and second are noted when it says: 'She sought wool and flax'; and the third there: 'She worked by the counsel of her hands.'

There is a counsel by which we are instructed to discern what is lawful, what is fitting, and what is expedient for salvation according to the judgment of right reason; another is a counsel by which we are instructed to choose what is lawful, what is fitting, and what is expedient according to the command of a good will. The third is a counsel by which we are instructed to pursue what is lawful, what is fitting, and what is expedient according to the exercise of virtuous operation. And of this counsel it is said: 'She has worked by the counsel of her hands.'
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollationes%2520de%2520Septem%2520Donis%2FCollation%25207.html'
source_title="Collationes de Septem Donis, Collation 7"

[[commentary]]
quote='''
'She sought wool and flax.' Wool is that from which coarse garment is made; flax is that from which fine garment is made. From wool is made a warm garment, from flax a delicate garment. Likewise, from wool is made an outer garment, while from flax is made an inner garment. According to this threefold property there are three senses, namely the allegorical, anagogical, and tropological.

According to allegory, by wool and flax are signified the New and Old Testaments. According to anagogy, by wool, from which a warm garment is made, is signified the revelation of prayer, because prayer is like heat; by flax, from which a delicate garment is made, are signified delights. According to tropology, by wool are given to be understood outward things, and by flax the experiences of just men.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollationes%2520de%2520Septem%2520Donis%2FCollation%25207.html'
source_title="Collationes de Septem Donis, Collation 7"

[[commentary]]
quote='''
There is a threefold operation, namely to discern rightly, to choose well, and to pursue readily. Therefore it says: 'She has worked by the counsel of her hands.' She not only decreed and chose, but carried it through. It does not suffice to have a good will, unless a man wills to carry it out in deed, from the intellective power to the affective and from the affective to operation. The Philosopher says that three things are necessary for virtue, namely 'to know, to will, and to act unwaveringly.'
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollationes%2520de%2520Septem%2520Donis%2FCollation%25207.html'
source_title="Collationes de Septem Donis, Collation 7"

[[commentary]]
quote='''
"Who shall find a valiant woman?" Without doubt it was said in commendation of mother Church, and specially in commendation of the glorious Virgin. In which word she is commended for three things: first, for the strengthening of spiritual fortitude; second, for the fruitfulness of supernatural conception; and third, for the discretion of salutary counsel. The third is noted when it adds: "She hath sought wool and flax, and hath wrought by the counsel of her hands."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollationes%2520de%2520Septem%2520Donis%2FCollation%25205.html'
source_title="Collationes de Septem Donis, Collation 5"
