[[commentary]]
quote='''
Concerning the second allegory, about the blessed Virgin Mary, it is said in the Psalm: "He has pitched a tent there for the sun." Wherefore she is "as beautiful as the moon, as resplendent as the sun, as awe-inspiring as bannered troops." Hence she is a vessel able to contain light: "The sun, an admirable instrument, the work of the most High — shining gloriously in the firmament of heaven."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollations%2520on%2520the%2520Hexaemeron%2FCollation%252013.html'
source_title='Collations on the Hexaemeron, Collation 13'
