[[commentary]]
quote='''
All our merits are rooted in the merit of Christ, whether satisfactory for punishment or meritorious of eternal life, because we are worthy neither to be absolved from offense against the highest good, nor to gain the immensity of the eternal reward, which is God, except through the merit of the God-man, to whom we can and ought to say: "All our works you have wrought in us, O Lord." He, I say, is the Lord, to whom the Prophet says: "I said to the Lord: You are my God, for you have no need of my goods."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FBreviloquium%2FPart%25204.html'
source_title="Breviloquium"
