[[commentary]]
quote='''
Transgressors of the commandments plunge into abominable crimes. Of such transgressors the Psalm says: "My people did not hear My voice, and Israel did not attend to Me, and I dismissed them according to the desires of their hearts." For the Lord delivers such transgressors into the hands of demons.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollationes%2520de%2520Decem%2520Praeceptis%2FCollation%25201.html'
source_title="Collationes de Decem Praeceptis, Collation 1"
