[[commentary]]
quote='''
These Centers are the "seven golden lamp-stands," and Christ "in the midst of the seven lamp-stands," which are the seven illuminations of wisdom, that is, the metaphysical, the natural, the mathematical, the logical, the ethical, the political, and the theological. These are the "seven eyes" of the Lamb, and the seven days that followed upon the first light.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollations%2520on%2520the%2520Hexaemeron%2FCollation%25201.html'
source_title='Collations on the Hexaemeron, Collation 1'

[[commentary]]
quote='''
In the mystery of the disclosing of Scriptures, Christ is pointed to through the symbol of the One presiding, as is clearly shown through the "son of man... in the midst of the seven lamp stands" that have "seven stars," which are the "Seven Churches."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollations%2520on%2520the%2520Hexaemeron%2FCollation%252014.html'
source_title='Collations on the Hexaemeron, Collation 14'
