[[commentary]]
quote='''
The Apostle to the Romans: "Do you not know that the kindness of God leads you to repentance? But according to your hardness and impenitent heart, you treasure up for yourself wrath on the day of wrath and of the revelation of the just judgment of God."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCollationes%2520de%2520Septem%2520Donis%2FCollation%25202.html'
source_title="Collationes de Septem Donis, Collation 2"
