[[commentary]]
quote='''
Since from the beginning Christ was most holy, he could not advance in holiness for himself. He merited, however, for us, who by his merit are justified through grace, advance in justice, and are crowned with eternal glory.

And through this, all our merits are rooted in the merit of Christ, whether satisfactory for punishment or meritorious of eternal life, because we are worthy neither to be absolved from offense against the highest good, nor to gain the immensity of the eternal reward, which is God, except through the merit of the God-man.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FBreviloquium%2FPart%25204.html'
source_title="Breviloquium"
