[[commentary]]
quote='''
Let us oppress the just poor man etc. Here he describes the unjust life as regards the oppression of the good, first, because they oppress without reverence for the person: second, because without fear of justice, at the words: But let our strength etc.

(Vers. 10. 11.). Let us oppress: The Gloss: "It is the voice of the lost"; the just poor man, that is, anyone whatsoever: Job 24: "They have equally oppressed the meek of the earth." And let us not spare the widow: Psalm: "They slew the widow and the stranger" etc.; nor let us reverence the grey hairs of the aged of many years, that is, any old man whatsoever; Baruch 4: "They have not reverenced the old man."

Allegorically this is expounded concerning heretics, who do not spare the just poor man, that is, the Christian people; nor the widow, that is, the Church; nor the aged, that is, the Apostles and Prophets.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520Wisdom%2FChapter%25202.html'
source_title='Commentary on Wisdom, Chapter 2'
