[[commentary]]
quote='''
He has become for us an exposer. Here is set forth the moving cause on the part of thoughts, and first is touched upon the manifestation of the thoughts of the Jews through Christ; second, the effect of the manifestation, caused not on the part of Christ, but on the part of the Jews, namely their envy, at: He is grievous etc.

(Verse 14.). He has become for us an exposer, that is, a revealer, of our thoughts: The Gloss: "He brings our thoughts into the light," that is, he leads them out into knowledge; whence Matthew 9: "Why do you think evil in your hearts?" So traducere is understood in Matthew 1, namely as to expose, where it says: "He was not willing to expose her."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520Wisdom%2FChapter%25202.html'
source_title='Commentary on Wisdom, Chapter 2'
