[[commentary]]
quote='''
(Vers. 14.). And not only these things, supply: did they do, but there was also another regard of theirs, that is, their intention was perverse, since they received strangers unwillingly, although they ought to have been entreated, by the example of Abraham saying: "Lord, if I have found favor in your eyes, do not pass by your servant," Genesis eighteen. Nor only ought they to have been entreated, but even compelled, by the example of the two disciples, of whom Luke last chapter: "And they compelled him"; upon which Gregory says: "That strangers are not only to be invited to lodging, but even to be drawn in."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520Wisdom%2FChapter%252019.html'
source_title='Commentary on Wisdom, Chapter 19'
