[[commentary]]
quote='''
But how could anything, that is, any creature, endure, namely in its being: unless you had willed it, that is, unless you voluntarily preserved it by your goodness? as if to say: in no way: whence Gregory: "All things that exist would tend toward nothingness, unless they were sustained or held by the hand of the Creator". Or what had not been called by you, that is, unless you approved it by beholding it with your wisdom: Romans 4: "Who calls those things that are not," etc., would be preserved? as if to say: nothing.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bonaventure%2FCommentary%2520on%2520Wisdom%2FChapter%252011.html'
source_title='Commentary on Wisdom, Chapter 11'
