[[commentary]]
quote='''
After making this digression to scare them and to cause them to look forward to the hope given them, he then gives attention to the "rest," bringing out that in times past the inspired David foretold it to us.
'''
source_url=''
source_title="INTERPRETATION OF HEBREWS 4"
