[[commentary]]
quote='''
For this is the time for these who were brazen to receive retribution and for those unjustly enslaved by them to get their freedom.
'''
source_url=''
source_title="COMMENTARY ON ISAIAH 19:63.1-6"
