[[commentary]]
quote='''
It is not surprising that from a cruel father a savage son was born, who imitated the wicked deeds of his most wicked father. Of him the Lord says in the Gospel to the elders and the proud among the Jews: You are of your father the Devil, and you wish to do the desires of your father; for he was a murderer from the beginning (Jn. 8:44). And rightly the son of a murderer plans to commit murder, not only bodily but also spiritual, that is, the destruction of souls which die in sin and wickedness.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Rabanus%2520Maurus%2FCommentary_on_1_Maccabees.html'
source_title="Commentary on 1 Maccabees"
