[[commentary]]
quote='''
But what follows we cannot read without lament, when we see some, compelled by torments, apostatize from the religion of devotion; others, enticed by the desire of this world, fall back; others, deceived by the cunning of heretics, are led astray; and others, by their own lust and passion, return to the former filth of vices.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Rabanus%2520Maurus%2FCommentary_on_1_Maccabees.html'
source_title="Commentary on 1 Maccabees 2"

[[commentary]]
quote='''
Yet that which follows brings great joy, because Mattathias and his sons stood firm; since, without doubt, those persist in truth and righteousness who have deserved to be sons of the true Mattathias, that is, of Jesus Christ, and by keeping his faith and commandments, strive with unwavering spirit, through his grace, to obtain the rewards of eternal life.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Rabanus%2520Maurus%2FCommentary_on_1_Maccabees.html'
source_title="Commentary on 1 Maccabees 2"
