[[commentary]]
quote='''
And the king himself pledges that he will agree to her request, just as he says in the Gospel: "Ask and it shall be given to you; seek and you shall find; knock and it shall be opened to you" (Matthew 7). And likewise: "Seek and you will receive, so that your joy may be complete." For complete joy is given to the holy Church solely in the sense that it partakes in the kingdom of Heaven, where the fortunate queen will rule forever with Christ the king.
'''
source_url='https://sites.google.com/site/aquinasstudybible/home/esther/rabanus-maurus-commentary-on-esther'
source_title='Commentary on Esther'

[[commentary]]
quote='''
And with regard to her petition, the king answered that he would listen to it, as it is said in the gospel as well, "Ask, and it will be given you; seek and you will find; knock, and the door will be opened for you." And again: "Ask, and you will receive, that you joy may be full." Indeed the full joy of the church is provided nowhere but in the perception of the heavenly kingdom where the queen will happily reign with the king Christ forever.
'''
source_url=''
source_title="EXPLANATION ON THE BOOK OF ESTHER 8"
