[[commentary]]
quote='''
By what they say, This is the Son, He manifestly proves that the rulers of the Jews crucified the Son of God, not through ignorance, but through jealousy. For they understood that it was He to whom the Father speaks by the Prophet, Ask of me, and I shall give thee the heathen for thine inheritance (Ps. 2:8.) The inheritance given to the Son is the holy Church; an inheritance not left Him by His Father when dying, but wonderfully purchased by His own death.

Or, The Jews endeavoured by putting Him to death to seize upon the inheritance, when they strove to overthrow the faith which is through Him, and to substitute their own righteousness which is by the Law, and therewith to imbue the Gentiles. It follows, And they caught him, and cast him out of the vineyard, and slew him.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Matthew%2FChapter%252021.html'
source_title='Catena Aurea by Aquinas'
