[[commentary]]
quote='''
He names branches as the sayings of perverse scriptures, and the fruits as the meanings of those sayings; by winds, he also signifies either the troubles of persecutions or the debates of judgment: because just as fragile branches are broken by the wind, so their imperfect sayings, when struck by any hardship or debate, are easily broken, and their fruits are useless and bitter, because the meanings of their words are depraved and poisonous, and therefore suited to no usefulness.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Rabanus%2520Maurus%2FCommentary_on_the_Wisdom_Of_Solomon.html'
source_title="Commentary on Wisdom, PL 109"
