[[commentary]]
quote='''
For by the wondrous works of the almighty God the faithful are instructed to beware of involving themselves in the sins of the wicked, and rather to strive to keep themselves untainted by such matters, and by maintaining faith and hope in the Lord, not to neglect the time granted to them for doing penance and good works; indeed, with all their strength, through love, they should try to serve their Creator.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Rabanus%2520Maurus%2FCommentary_on_the_Wisdom_Of_Solomon.html'
source_title="Commentary on Wisdom, PL 109"
