[[commentary]]
quote='''
To those who, through ignorance or weakness or even necessity, have committed certain crimes, and yet have not ceased through humility and repentance to erase those sins, the most merciful Judge grants the grace of forgiveness. But for those who, through stubbornness and contempt for the commandments of God, have committed many and grave crimes, and have neglected to repent of them, more severe torments are assigned in Hades: for just as they were more powerful in the act of wickedness, so they endure stronger punishments in the fire of Gehenna.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Rabanus%2520Maurus%2FCommentary_on_the_Wisdom_Of_Solomon.html'
source_title="Commentary on Wisdom, PL 109"
