[[commentary]]
quote='''
They that are carnal cannot do those things which are spiritual, nor they that are spiritual the things which are carnal; even as faith cannot do the works of unbelief, nor unbelief the works of faith. But ye, being full of the Holy Spirit, do nothing according to the flesh, but all things according to the Spirit. Ye are complete in Christ Jesus, "who is the Saviour of all men, specially of them that believe."
'''
source_url="https://historicalchristian.faith/by_father.php?file=Ignatius%2520of%2520Antioch%2FEpistle%2520to%2520the%2520Ephesians.html"
source_title="Epistle of Ignatius to the Ephesians"
