[[commentary]]
quote='''
With good reason were they moved at sight of a thing so to be wondered at. Man was praised as God, but it was the God that was praised in the man. But, I suppose, that neither they who praised knew what they praised, but the Spirit that suddenly inspired them poured forth the words of truth.
'''
time=1274
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Matthew%2FChapter%252021.html'
source_title='Catena Aurea by Aquinas'
