[[commentary]]
quote='''
Holy Job had not only shown that Zophar’s words were ridiculous but also had reproved all his friends in common. They all thought that wisdom had to be judged according to the limits of their age. Since he had also discussed many issues concerning both human and divine nature, Eliphaz gets offended. He tries to accuse [Job] openly of different iniquities; since he has no decisive evidence, Eliphaz takes refuge by drawing a comparison with the people of previous generations, without showing any humility but by considering himself to be wiser than anybody else.
'''
source_url=''
source_title="EXPOSITION ON THE BOOK OF JOB 15:1-3"
