[[commentary]]
quote='''
And because, if in these ways men return out of great destruction to great repentance, they are not only useful to themselves, but they are able also to be of advantage to many, He promised them no small reward,-to sit, namely, on the throne of judgment.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Victorinus%2520of%2520Pettau%2FCommentary%2520on%2520the%2520Apocalypse%2520of%2520the%2520Blessed%2520John.html"
source_title="Commentary on the Apocalypse of the Blessed John"
