[[commentary]]
quote='''
And in that he says that the sun is not necessary in the city, he shows, evidently, that the Creator as the immaculate light shines in the midst of it, whose brightness no mind has been able to conceive, nor tongue to tell.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Victorinus%2520of%2520Pettau%2FCommentary%2520on%2520the%2520Apocalypse%2520of%2520the%2520Blessed%2520John.html"
source_title="Commentary on the Apocalypse of the Blessed John"
