[[commentary]]
quote='''
Scarioth is interpreted 'The memory of the Lord,' because he followed the Lord; or 'The memorial of death,' because he plotted in his heart how he might betray the Lord to death; or 'strangling,' because he went and hanged himself. It should be known that there are two disciples of this name, who are types of all Christians; Jude the brother of James, of such as persevere in the confession of the faith; Jude Scarioth of such as leave the faith; and turn back again.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Matthew%2FChapter%252010.html'
source_title='Catena Aurea by Aquinas'
