[[commentary]]
quote='''
"Therefore, it seems strange to them." They are amazed, that is, they admire. This is what he says: When you have once renounced the pursuits of the Gentiles, which you once lived by, you adhere to the honorable life that you have assumed. For even the Gentiles admire you, that you do not rush into a similar outpouring or confusion of impiety. And therefore, they not only admire and marvel at your strange transformation, not only are they ashamed, but they also slander you, that is, they mock you. For divine worship is an abomination to the sinner.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520the%2520Catholic%2520Epistles%2FTranslation-Litteral.html'
source_title='Commentary on 1 Peter'
