[[commentary]]
quote='''
Standing and not sitting, the blessed Stephen sees Jesus, in order to show the attention directed toward him, and to provide the contestant with great eagerness; the posture of the one assisting is shown: Moreover, since sitting was burdensome for them, he said first that he stood, hinting at his resurrection; but because he does not stand, but sits, Paul indicated by saying that he raised and sat down together, at his right hand in the heavenly places. [CHRYSOSTOM]
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520Acts%2FTranslation-Litteral.html'
source_title='Commentary on Acts'
