[[commentary]]
quote='''
They fulfill what the Lord commanded them, saying: "If anyone does not receive you, shake off the dust from your feet." (Matt. 10:14, Mark 6:11, and Luke 9:5) But these not only did not receive them, but even drove them out of their borders, which is worse. For the Lord does not wish his disciples to have even the dust on their feet from the land of wicked people, thereby showing that they had gained nothing from the disobedient. The dust is a token of the toil which they endured on their behalf. [CHRYSOSTOM]
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520Acts%2FTranslation-Litteral.html'
source_title='Commentary on Acts'
