[[commentary]]
quote='''
For the phrase "for a time," giving a limit to the sentence, means that the way in which he received the light is to be altered for the better; for he who had been led to the worse was now to be brought to this as well. Accordingly it was not punishment but healing.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520Acts%2FTranslation-Litteral.html'
source_title='Commentary on Acts'
