[[commentary]]
quote='''
Having begun he added: "From the baptism of John." For concerning this, none of them knew, having learned and being present, except only the one chosen; but the Spirits perceived. And he declared him a witness of the resurrection. For this is above all the chief point of Jesus' divinity. Since also regarding his miracles before the passion, many were witnesses and even the unbelieving who had seen them.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520Acts%2FTranslation-Litteral.html'
source_title='Commentary on Acts'
