[[commentary]]
quote='''
He calls them devout [Σεβομένους] Greeks, who, although they were from the Jews, nevertheless spoke Greek: devout because they observed the law; or proselytes of the Jews who were from the Greeks.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520Acts%2FTranslation-Litteral.html'
source_title='Commentary on Acts'
