[[commentary]]
quote='''
Yet they do not lead the apostles before Pilate as they did Christ, but they themselves judge: first indeed affected by shame and modesty, then fearing for fear that they too be accused by these concerning him.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520Acts%2FTranslation-Litteral.html'
source_title='Commentary on Acts'
