[[commentary]]
quote='''
"I do not nullify the grace." As those who still observe to the law are now nullifying the grace through Christ. To nullify is to disbelieve, to despise, to mock. Do you see where he led the argument?

"For if righteousness comes through the law." For if, he says, the law is able to save and to justify, Christ died in vain. For this reason he delivered up himself, as if the law had no power, so that he might save by his death. If indeed the law were saving, the death of the Lord would be unnecessary.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520Galatians%2FTranslation-Litteral.html'
source_title='Commentary on Galatians'
