[[commentary]]
quote='''
"Become as I am." Yet the words are addressed to those from Judea. Become as I am. "Be imitators of me," Paul says, "for I also, having set aside the law, ran to faith." For even I, he says, was as you are, observing the law and carefully practicing it in many respects.

"for I also am as you are." I longed intensely for the law as well, but see how I have been changed. "You also," he says, "envy that change."

— [PHOTIUS] He appeals to them, considering their salvation as his own. He passes through their acts of gratitude, and the honors by which they honored him, and how greatly they regarded him, wishing to set this right, namely, that the insults now uttered against them by him were not spoken out of any dislike or hatred (for how, he says, could he have been hostile toward you, having treated you with great consideration?); but that what was said came from a mind that was anxious and loving.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520Galatians%2FTranslation-Litteral.html'
source_title='Commentary on Galatians'
