[[commentary]]
quote='''
So that they might not say, "What great thing have we done by keeping only one commandment of the law?" he says, "One?" and what is that?

"A little yeast infuses the whole batch of dough." For just as that infuses the whole batch, he says, so your circumcision will certainly bring in Judaism to perfection, unless you are corrected.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520Galatians%2FTranslation-Litteral.html'
source_title='Commentary on Galatians'
