[[commentary]]
quote='''
"on the contrary." Not only, he says, did they not correct anything concerning my preaching, but on the contrary, they praised it. And this arrangement is as follows: "on the contrary, knowing that I had been entrusted with the Gospel of the uncircumcision," the rendering with much, they say, "They gave me and Barnabas the right hand of fellowship." (Galatians 2:9) This, then, is to correct the opposite, namely to take the right hand, which was a sign of receiving their proclamation.

"the Gospel of the uncircumcision." As in the case of the uncircumcised nations. See how Paul equates himself to Peter. For this one indeed needed favor, so that he might appear credible to the Galatians.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520Galatians%2FTranslation-Litteral.html'
source_title='Commentary on Galatians'
