[[commentary]]
quote='''
So also Christ did not glorify himself to become a high priest. He also says this: "Christ is the first high priest, that he did not enter into the priesthood from himself, but was ordained by the Father." Therefore, showing in clear terms that he was a priest according to the custom of the priests, in other respects he indicates how much he ought to excel as God of men.
"but it was He who said to him." He says, God having said this to him, ordained him as high priest,
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title='The Pseudo-Oecumenian Catena on Hebrews'
