[[commentary]]
quote='''
"the tabernacle and." And the tabernacle was a type of the faithful, because of, "I will dwell in them and walk among them." (Lev. 26:12; 2 Cor. 6:16)
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title='The Pseudo-Oecumenian Catena on Hebrews'
