[[commentary]]
quote='''
"there must also of necessity be the death of the one who made it," This is what disturbs them, the death of Christ. For how, he says, can the one who has died give us the promises? Therefore, he turns and shows that we can only receive the inheritance and the promise if Christ has died. For if he had not died, he would not have made a will, so that we might inherit; (for it is indisputable that a will is in force only after death;) nor would we be worthy of an inheritance at all, as long as the enmity remains unresolved.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title='The Pseudo-Oecumenian Catena on Hebrews'
