[[commentary]]
quote='''
For this reason, he now cites it. What is man that you are mindful of him? Since it seemed to oppose his purpose, he indeed shows that Christ is greater than the angels, yet he says that he was made a little lower than the angels. He presents this in order to resolve the objection that seems to arise, and in resolving it, he says that he was made lower because of the passion of death. "For we saw him and he had neither form nor beauty." (Isa. 53:2)
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title='The Pseudo-Oecumenian Catena on Hebrews'

[[commentary]]
quote='''
"You made him a little lower than the angels." Here he recalls the declaration after the transgression. For the mortal is made lower than the angels.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title='The Pseudo-Oecumenian Catena on Hebrews'
