[[commentary]]
quote='''
— "But Christ as a Son." For even if he is called faithful, Paul says, it is as a genuine Son that he is faithful, fulfilling the will of the Father, rather the common will of the holy Trinity.
"whose house we are."Here we are the house of Christ, the faithful, according to what is written: "I will dwell in them." (Lev. 27:12; 2 Cor. 6:16) —
"if we hold fast the confidence." We shall be his house if we do not shrink back because of the faith that belongs to him, but boast with boldness, and hope to receive good things from Him as God, not being shaken or doubting in anything.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title='The Pseudo-Oecumenian Catena on Hebrews'
