[[commentary]]
quote='''
"an end of all dispute." And the conclusion of all contradiction and dispute to confirm what is said is the oath. For indeed many things are spoken and disputed on each side; but the oath, coming last and confirming, resolves all doubts.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title='The Pseudo-Oecumenian Catena on Hebrews'
