[[commentary]]
quote='''
He also urged the younger men to be sensible; presenting yourself as a pattern of good works in everything, in teaching, showing incorruptibility, dignity, sound speech, and blamelessness; so that the opponent may be ashamed, having nothing evil to say about us.

Do you see how appropriately Paul arranged it, appointing women as teachers of women and elderly women, and Titus himself to the men?

to be sensible. For nothing is so hostile to youth as the erotic love [ἔρως] of the body.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520the%2520Catholic%2520Epistles%2FTranslation-Litteral.html'
source_title='COMMENTARY ON TITUS'
