[[commentary]]
quote='''
For some of the angels were commissioned to move the air, some the sun, some the moon, some the stars, while others prepared the clouds and the rains, and rendered many other services— for this is the work, the appointed duty, of the angelic orders and powers—to minister to the well-being and honour of the image of God, that is, of man, and to move all things like soldiers obeying the commands of the king. This work they were commanded to do on the fourth day, when God adorned the heaven with its stars. The work of the adverse demons, as rebels against God, is to do what will mar his image, for on the fourth day they transgressed the command and were cast out of heaven, as elsewhere he says: Are they not all ministering spirits sent forth to minister to those who shall be the heirs of Salvation? thus expressly declaring that they were ordained for the service of man
'''
source_url="https://historicalchristian.faith/by_father.php?file=Cosmas%2520Indicopleustes%2FThe%2520Christian%2520Topography%2FBook%25202.html"
source_title="The Christian Topography, Book 2"

[[commentary]]
quote='''
Are they not all ministering spirits, sent forth to do service for the sake of them that shall inherit salvation?
'''
source_url="https://historicalchristian.faith/by_father.php?file=Cosmas%2520Indicopleustes%2FThe%2520Christian%2520Topography%2FBook%25205.html"
source_title="The Christian Topography, Book 5"

[[commentary]]
quote='''
The language of the Apostle also: Are they not all ministering spirits sent forth to minister for the sake of them that shall inherit salvation? very clearly shows that they all for the sake of man are occupied night and day in their ministrations and services, and in doing everything else towards giving men relaxation from their toils and towards supplying their wants. For, when we shall no longer need them, they shall be set free from this bondage and service, and shall cast down the stars upon the earth.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Cosmas%2520Indicopleustes%2FThe%2520Christian%2520Topography%2FBook%25209.html"
source_title="The Christian Topography, Book 9"

[[commentary]]
quote='''
Are they not all ministering spirits sent forth to do service for the sake of them that shall inherit salvation? saying here, that all of them together have been ordained for service to men, as living with them in this place.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Cosmas%2520Indicopleustes%2FThe%2520Christian%2520Topography%2FBook%25207.html"
source_title="The Christian Topography, Book 7"
