[[commentary]]
quote='''
For the very Prophet through whom the retrogression of the sun was effected, when, by means of the dread sign, he had in reality confuted the theory of the Babylonians, by showing that the heaven is not a revolving sphere, and that they held an opinion that is erroneous, this very Prophet not long afterwards speaks thus of the figure of the heaven: He that established the heaven as a vaulted chamber; and again: The Lord God who made the heaven and fixed it, thus declaring at once that it is a vault, and that it is established and fixed and not in revolution
'''
source_url="https://historicalchristian.faith/by_father.php?file=Cosmas%2520Indicopleustes%2FThe%2520Christian%2520Topography%2FBook%25208.html"
source_title="The Christian Topography, Book 8"
