[[commentary]]
quote='''
as the Lord also in the Gospels speaks thus concerning the consummation: For the powers of heaven shall be shaken, thus calling the angels the powers of heavens, and by the expression they shall be shaken, He means they shall be set free from their former office. As the angels, therefore, who move the stars themselves and other things, are certainly set free from this office and ministry, He declares that the stars fall to the earth.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Cosmas%2520Indicopleustes%2FThe%2520Christian%2520Topography%2FBook%25209.html"
source_title="The Christian Topography, Book 9"
