[[commentary]]
quote='''
But without law it is impossible there should be transgression, as saith the Apostle: For where there is no law there is no transgression, and Without the law sin is dead. So that the angels themselves in every way want to obtain freedom from the law and from mutation
'''
source_url="https://historicalchristian.faith/by_father.php?file=Cosmas%2520Indicopleustes%2FThe%2520Christian%2520Topography%2FBook%25202.html"
source_title="The Christian Topography, Book 2"
