[[commentary]]
quote='''
The timbers of Lebanon are declared to be imperishable. Therefore King Solomon made himself a litter from the timbers of Lebanon, because, according to the grace of His foreknowledge, Christ built the holy Church from saints who would endure forever.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Robert%2520of%2520Tombelaine%2FCommentary%2520on%2520the%2520Song%2520of%2520Songs.html'
source_title='Commentary on the Song of Songs, Chapter 3'
