[[commentary]]
quote='''
(Serm. 50.) The Creator of all things, the Lord of the world, when He had for our sakes straitened Himself in the bonds of our flesh, began to have His own country as a man, began to be a citizen of Judæa, and to have parents, though Himself the parent of all, that affection might attach those whom fear had separated.

(ubi sup.) Christ has no need of the vessel, but the vessel of Christ; for without heavenly pilotage the bark of the Church cannot pass over the sea of the world to the heavenly harbour.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Matthew%2FChapter%25209.html'
source_title='Catena Aurea by Aquinas'
