[[commentary]]
quote='''
He brought to mind an Old Testament saying (see Deut. 13:5), wishing to show that already before it was pleasing to the lawgiver that impious people be cut off from the community. With the words "from among you" he shows that it will be more beneficial for them if they cast out the impious one from themselves.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Corinthians%2FChapter%25205.html'
source_title='Commentary on 1 Corinthians'
