[[commentary]]
quote='''
Here he proves the justice of the cause. You, he says, repay unequally for what you have received. For we sowed in you spiritual things, and you repay us with carnal things. Is this a great thing?
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Corinthians%2FChapter%25209.html'
source_title='Commentary on 1 Corinthians'
