[[commentary]]
quote='''
That is, do we really not have the authority to live without working and to be supported at the expense of our disciples, without laboring? He did not fail to mention Barnabas either, who, as he knew, was also scrupulous in this regard; for he lived by his own labor.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Corinthians%2FChapter%25209.html'
source_title='Commentary on 1 Corinthians'
