[[commentary]]
quote='''
In order not to appear proud, he also takes them as partners: for he says, "in your assembly in the name of our Lord Jesus Christ," that is, so that the assembly would be constituted not according to human custom, but according to God; so that Christ Himself would gather you, in whose name you also assemble. Meanwhile, the apostle also placed his spirit over them, so that they would not grant the fornicator forgiveness, but would judge justly, as in the presence of the apostle.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Corinthians%2FChapter%25205.html'
source_title='Commentary on 1 Corinthians'
