[[commentary]]
quote='''
Not immediately does he begin speaking about the meals, but first reproaches them for the fact that there are divisions among them. For indeed, it was precisely because there were divisions among them that each one ate separately.

So that they would not say that those who slander us are lying, he said neither "I believe," lest he make them more shameless, nor "I do not believe," lest he appear a groundless accuser, but: I partly believe. And indeed it is likely that not all violated this custom, but a "part," that is, some.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Corinthians%2FChapter%252011.html'
source_title='Commentary on 1 Corinthians'
