[[commentary]]
quote='''
In my opinion, he says, it is best of all for a person to abstain from marriage on account of the inconveniences and unpleasantnesses connected with it, and not because marriage is impure.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Corinthians%2FChapter%25207.html'
source_title='Commentary on 1 Corinthians'
