[[commentary]]
quote='''
Purge out therefore this fornicator, or rather, drive out all other wicked persons as well (for by "old leaven" he means every kind of evil). In the Greek text it does not simply say "cleanse" (καθάρατε), but "purge out" (ἐκκαθάρατε), that is, cleanse completely, that you may be a new lump, having no admixture of evil. "Since you are unleavened," instead of: as you ought to be unleavened, that is, free from the old evil, which upon repentance proves to be both sour and bitter.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Corinthians%2FChapter%25205.html'
source_title='Commentary on 1 Corinthians'

[[commentary]]
quote='''
Having mentioned the unleavened breads, the azymes, which were eaten as food at Pascha, and having explained allegorically what the unleavened breads signify, namely a life free from evil, he now allegorically explains Pascha itself and says that our Pascha is Christ, slain for us. Therefore, we must take care concerning the unleavened breads, that is, a life pure from all evil.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Corinthians%2FChapter%25205.html'
source_title='Commentary on 1 Corinthians'
