[[commentary]]
quote='''
That is, do not give anyone any occasion for reproach. And this will be the case when we do not cause offense to either Jew or Greek, and still less to the brethren, for they are the "church of God." Take note. He stated the most important thing at the end: Christians ought to attract others to the faith as well, rather than persecuting even the brethren; and by them he means all those who were scandalized by their eating of food offered to idols.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Corinthians%2FChapter%252010.html'
source_title='Commentary on 1 Corinthians'
