[[commentary]]
quote='''
Here He mentioned also the Father, Who produces operations in all believers. And behold for you the perfect Trinity. Now the gift, and the operation, and the ministry are one and the same thing, although they differ in names: for they are equally given by the Spirit, and by the Son, and by the Father. Notice also that he mentioned the Spirit first, and the Father last: this is for the sake of those who are too particular about order.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Corinthians%2FChapter%252012.html'
source_title='Commentary on 1 Corinthians'
