[[commentary]]
quote='''
If you do not intend to eat all together, then why do you not eat at home?

For when you turn the Lord's Supper into a private one, eating by yourself, you show contempt both for the church and for the place.

The poor are troubled not so much by the fact that you do not feed them, as by the fact that you put them to shame, exposing their poverty, while you yourselves recline grandly and drink to excess.

Having rebuked them for their error, he softens his speech. He could have said that this is worthy of a thousand deaths; but what does he say? "Shall I praise you? In this I will not praise you." He does this in order to make them more condescending toward the poor. For if he had extended his strong rebuke to the end, they would have hardened themselves against the needy, since the apostle reproaches them on their account.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Corinthians%2FChapter%252011.html'
source_title='Commentary on 1 Corinthians'
