[[commentary]]
quote='''
Perfect love, he says, is proven by deeds. But since it happens that someone outwardly appears to observe the commandments correctly and precisely, yet his inner disposition is impure, which is why he is far from God, the apostle says that one who has drawn near to God must live as closeness to God requires.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520John%2FChapter%25202.html'
source_title='Commentary on 1 John'
