[[commentary]]
quote='''
This refers to what was said a little above (v. 2): every spirit that confesses the Lord Jesus, who has come in the flesh. The apostle has sufficiently proved that believers are children of God and that God abides in them; and he proved this by love for one another, because the Holy Spirit was given to them. After this he returns to the aforementioned discourse and says: whoever confesses that Jesus is the Son of God, God abides in him, because, as was said above, every spirit that confesses Jesus Christ, who has come in the flesh, is from God.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520John%2FChapter%25204.html"
source_title = "Commentary on 1 John"
