[[commentary]]
quote='''
By the ungodly He is blasphemed, but by you He is glorified. Why? Because when their accusation against you proves to be false, shame will befall them, and glory will be yours.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Peter%2FChapter%25204.html'
source_title='Commentary on 1 Peter'
