[[commentary]]
quote='''
Such was the care of the holy apostle Paul for his disciples, that when he himself was detained by some difficult circumstances, he would send others to visit his disciples. This is what he did then as well, sending Timothy. And he speaks of him with such praise, not so much exalting him as honoring them by the fact that one so indispensable at such a time he drew away for their sake from the work of ministry as a "fellow worker in the Gospel."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Thessalonians%2FChapter%25203.html'
source_title='Commentary on 1 Thessalonians'

[[commentary]]
quote='''
Since the Thessalonians were troubled by the fact that their teacher was subjected to trials, they had need of strengthening and consolation, so as not to fall away from the faith. For the trials of a teacher cause no small disturbance to the disciples, just as the wounds of a commander do to the soldiers.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Thessalonians%2FChapter%25203.html'
source_title='Commentary on 1 Thessalonians'
