[[commentary]]
quote='''
Not only from this or that, but simply from everything: both from false prophets and from sin.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Thessalonians%2FChapter%25205.html'
source_title='Commentary on 1 Thessalonians'
