[[commentary]]
quote='''
O Paul! If you predicted to them that you would endure affliction, and that they should not be troubled by this affliction, then why do you send again? It turns out that you do not yet fully trust them. Out of great love, he says, I do this. For those who love are anxious even about what is safe. At the same time, the temptations were many, and the excessive multitude of calamities frightened me. Therefore he did not say: having noticed something in you, I sent, but "being unable to bear it any longer," which comes from love.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Thessalonians%2FChapter%25203.html'
source_title='Commentary on 1 Thessalonians'

[[commentary]]
quote='''
Here some ask: why did he who was caught up to the third heaven, who heard inexpressible words (2 Cor. 12:6), not know what was happening with the Thessalonians, but sent Timothy "to learn about their faith"? One may say that not everything was known even by the saints who lived before Christ and after Christ. For Elisha too did not know about the Shunammite woman (2 Kings 4:8). And Elijah thought that he alone was left, while there were still seven thousand others (1 Kings 19:10). And before them, Samuel receives instruction not to pay attention to the appearance of David's eldest brother (1 Sam. 16:7). So the apostles too did not know everything. And this was by the special providence of God, so that neither would they themselves become proud, nor would others think too highly of them, and so that later Christians could not say that they performed feats of virtue because they were above ordinary men, and therefore give themselves over to negligence; but rather, so that we would know that even they did not always rely on the help of God, but accomplished their feats through their own labors.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Thessalonians%2FChapter%25203.html'
source_title='Commentary on 1 Thessalonians'

[[commentary]]
quote='''
I, he says, did not suppose that you were shaken, except perhaps because you were subjected to temptations. Do you see that disturbance in afflictions is the work of the devil, and especially when some are scandalized as a result of others experiencing misfortune? So he acted with Job, troubling his wife by the fact that he was suffering. However, the devil tempts without knowing whether he will prevail, as is evident from the example of Job; yet, being shameless, he attacks, and if he sees any weakness, he remains and waits; but if he sees strength, he retreats.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Thessalonians%2FChapter%25203.html'
source_title='Commentary on 1 Thessalonians'

[[commentary]]
quote='''
If they had gone astray, O Paul, what is that to you? Your labor will not remain without full reward from God. However, he says, on account of my strong love, I would have considered my labor lost.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Thessalonians%2FChapter%25203.html'
source_title='Commentary on 1 Thessalonians'
