[[commentary]]
quote='''
The greatest consolation for the righteous consists in the fact that good and evil deeds are known even here, but especially there, where all things are laid bare.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Timothy%2FChapter%25205.html'
source_title='Commentary on 1 Timothy'
