[[commentary]]
quote='''
The Apostle speaks here not of one who was young in age, as Timothy was young, which we learn from Paul's words: "let no one despise your youth" (1 Tim. 4:12), but of a recent convert. For, he says, "I planted" (1 Cor. 3:6). Since many of the pagans were converting and being baptized, do not, he says, immediately elevate the newly baptized to such authority.

If anyone, before being a proper disciple, becomes a teacher, he will, he says, become puffed up and fall under the same condemnation and punishment to which the devil is subject for his pride.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Timothy%2FChapter%25203.html'
source_title='Commentary on 1 Timothy'
