[[commentary]]
quote='''
Lest by giving him instruction concerning such matters he cast the disciple into grief, as though Paul would no longer see him, he says: I do not write this because I will no longer come; on the contrary, I will come. However, if it happens that I am delayed, you must have a model of how it is fitting for you to live. The apostle said beautifully: "hoping." Since, being led by the Spirit, he did not know where he must go, he rightly has doubts also concerning his coming to Timothy.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25201%2520Timothy%2FChapter%25203.html'
source_title='Commentary on 1 Timothy'
