[[commentary]]
quote='''
And hinting at the false apostles, who said that through their mediation the blessings of God were communicated to their disciples, he says: "all things are for your sakes," even the resurrection itself, and not for the sake of this one or that one. God does this and grants grace to many, so that as grace abounds, thanksgiving also may abound, being offered by many to the glory of God. Therefore the false apostles, by attributing the grace of God to themselves, also obscure its glory.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25202%2520Corinthians%2FChapter%25204.html'
source_title='Commentary on 2 Corinthians'
