[[commentary]]
quote='''
What are you saying? Those who preach Christ, who do not introduce a different Gospel, as he said above, have now become false apostles? Yes, he says, for this very reason; for, being hypocritical in this, they secretly introduce impious dogmas. And "evil workers," because they only appear to be building up, but in reality they uproot what had been planted, and, having only the outward appearance of apostles, are truly wolves in sheep's clothing.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25202%2520Corinthians%2FChapter%252011.html'
source_title='Commentary on 2 Corinthians'
