[[commentary]]
quote='''
Finally, just as he ends the first epistle with a prayer, so also in the second he asks for their growth in the faith of the Lord.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25202%2520Peter%2FChapter%25203.html'
source_title='Commentary on 2 Peter'
