[[commentary]]
quote='''
He himself had previously prayed for them, that they might be established in the faith; now he asks them to pray for him, not asking that he not be subjected to dangers (for he had devoted himself to this), but that "the word of the Lord may spread and be glorified." Here the request is joined with praise: "as," he says, "among you," so that all might likewise submit to it, as you did. Thus the apostle asks nothing for himself personally, but everything for God's sake.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25202%2520Thessalonians%2FChapter%25203.html'
source_title='Commentary on 2 Thessalonians'
