[[commentary]]
quote='''
That is, those who slander everyone. A person who is not conscious of anything good in himself slanders everyone, inventing and finding in this, it would seem, a certain consolation for himself.

And in the tongue, and in the belly, and in everything else.

You see what self-love and love of money make people? Beasts instead of men.

Enemies of every good thing.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%25202%2520Timothy%2FChapter%25203.html'
source_title='Commentary on 2 Timothy'
