[[commentary]]
quote='''
"But I," said God, "will judge that nation which they shall serve..." Those who afflicted them did not do so with impunity, because the Jews endured bitter and harsh slavery, since the Egyptians regarded them not as slaves, but as enemies and adversaries.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Acts%2FChapter%25207.html'
source_title='Commentary on Acts'
