[[commentary]]
quote='''
Simon was known as a man close in time, but he did not have authority, since he was not an ancient man. Therefore James brings forth an ancient prophecy: "After this I will return and will rebuild the tabernacle of David which has fallen." The fall was so great that it seemed irreparable. What then? Was Jerusalem restored? Was it not destroyed even more? What restoration then does the prophecy speak of? Of the restoration after the Babylonian captivity, when Jerusalem again came to have significance.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Acts%2FChapter%252015.html'
source_title='Commentary on Acts'
