[[commentary]]
quote='''
"Let these same men say what wrong they found in me." They found wrong at the assembly, when an inquiry was made. And that I speak the truth, my very accusers themselves testify to this. Not to avoid one's accusers, but to be ready to give an answer to everyone, is a sign of undoubted righteousness.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Acts%2FChapter%252024.html'
source_title='Commentary on Acts'
