[[commentary]]
quote='''
"I stand before Caesar's judgment seat" means: I wish to go to Rome to Caesar and there receive judgment. I demand this, he says, from you.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Acts%2FChapter%252025.html'
source_title='Commentary on Acts'
