[[commentary]]
quote='''
"You sit to judge according to the law, and, contrary to the law, you order me to be struck." That is, transgressing the law, becoming guilty of lawlessness; as if to say: "Being worthy of very many punishments."

"You whitewashed wall!" He calls him this because although Ananias assumed the bright appearance of a man who supposedly defends the law and judges according to the law, his mind was full of lawlessness. Therefore Paul also exposes in him the hypocritical appearance of outward devotion to the law.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Acts%2FChapter%252023.html'
source_title='Commentary on Acts'
