[[commentary]]
quote='''
"The commander, fearing." He was afraid lest they tear Paul apart, since he had said that he was a Roman, and the matter was not far from danger. Finally the soldiers snatch him away, I think, as their own property.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Acts%2FChapter%252023.html'
source_title='Commentary on Acts'
