[[commentary]]
quote='''
He gently rebukes them, showing that they acted rashly and that it was not proper to hold a public assembly for private reasons.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Acts%2FChapter%252019.html'
source_title='Commentary on Acts'
