[[commentary]]
quote='''
He did not say "I took neither silver, nor gold, nor clothing," but even "I did not desire them."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Acts%2FChapter%252020.html'
source_title='Commentary on Acts'
