[[commentary]]
quote='''
See how he does not finish speaking about the essence of the matter, about the promised seed. He did not bring forward the testimony on which they could rely that the remission of sins is accomplished through Jesus, and this was beyond doubt.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Acts%2FChapter%252013.html'
source_title='Commentary on Acts'
