[[commentary]]
quote='''
The Jews had the custom of reading on the Sabbath the Law of Moses and the Prophets, and after the reading, of addressing the people with a speech and explaining what had been read. Therefore the rulers of the synagogue invite those who were with Paul to speak in the synagogue.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Acts%2FChapter%252013.html'
source_title='Commentary on Acts'
