[[commentary]]
quote='''
But do you see Paul's fiery zeal? After he was cast out of the city, he came again to that very same city, to show that if anywhere, in such cases, he did withdraw, it was because he had to sow the word of God and that it was not fitting to inflame wrath.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Acts%2FChapter%252014.html'
source_title='Commentary on Acts'
