[[commentary]]
quote='''
Having spoken about what we have received, Paul points to yet another advantage, namely that before us no one knew this mystery. He calls a mystery that which no one knew except God, and not simply "hidden" (κεκρυμμένον), but "concealed" (ἀποκεκρυμμένον). And the expression "from the ages" means: since the ages began.

This is His dispensation, that the mystery is now revealed. He did not say "accomplished," but "revealed." However, even now it is not for all, but for His saints. So that even now it remains hidden from some. Therefore let not those people deceive you, for they do not know it.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Colossians%2FChapter%25201.html'
source_title='Commentary on Colossians'
