[[commentary]]
quote='''
"Zeal" and "great" – both words are placed together for emphasis. He praises Epaphras also to the Laodiceans and Hierapolitans, for they, having no doubt read the epistle, could hear about him.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Colossians%2FChapter%25204.html'
source_title='Commentary on Colossians'
