[[commentary]]
quote='''
Look how he brings them closer together, how he binds them to one another.

This was a famous man, whose entire household were believers, which is why his house was called a church. Therefore Paul also shows his affection toward him, greeting him separately. He does this also in order to urge others to the same zeal, so that others might imitate Nymphas, if they wish to be honored in the same way.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Colossians%2FChapter%25204.html'
source_title='Commentary on Colossians'
