[[commentary]]
quote='''
As at the beginning of the epistle, so also now he commends him, so that, as one who loves them, they would love him in return, and would willingly listen to him when he teaches anything. And that the teacher is a man worthy of respect is beneficial also for the students, since they will more readily believe his words. It is also great praise for Epaphras that he is a servant of Christ. So then, he is your glory, especially since he came forth from your midst.

Not simply did he say: praying for you, but with anxiety and trembling, – not on just one particular day, but always.

He gently rebukes them for their imperfection. For they are still not firm and waver in the teaching about angels. For it is possible to be both perfect and not standing firm, just as if someone were to learn everything but not be firmly established in anything. Therefore he says: "that you may stand perfect," meaning, in teaching and life.

That is, so that you would fulfill no other will except the will of God: for this means to be complete and perfect. By this he also shows that they partly still preserve some things from what was preached, and partly have already lost some things.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Colossians%2FChapter%25204.html'
source_title='Commentary on Colossians'
