[[commentary]]
quote='''
Since it is possible to please one another not out of pure love, but only in appearance and hypocritically, he shows the way by which we can attain true pleasing of others. One may be both meek and humble-minded, and yet not with love. Therefore he also says: "but above all these things put on love."

All the aforementioned virtues love binds together by its presence. When love is absent, everything vanishes and in reality nothing remains but hypocrisy. For just as in a house, if there were no crossbeams, commonly called ties, or if in a body there were no ligaments, then everything else would be useless: so too love unites all that contributes to perfection, and without it there is no perfection; although it may seem that someone possesses it, it is not perfection at all.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Colossians%2FChapter%25203.html'
source_title='Commentary on Colossians'
