[[commentary]]
quote='''
To discern is the task of the mature, who are able to judge. Therefore, it is characteristic only of an immature and ignorant understanding to choose what is not pleasing to the Lord, such as the aforementioned passions.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Ephesians%2FChapter%25205.html'
source_title='Commentary on Ephesians'
