[[commentary]]
quote='''
I, he says, ask, but He will do even more than what is contained in my prayer. For not only everything that one asks, but more He is able to do, and "incomparably more," that is, generously and abundantly. And he indicates the abundance twofold: "incomparably" and "more." For it is possible to do more than what is asked, but not "incomparably," which means generously and abundantly. But God can do both. As He indeed was able and accomplished in us great and extraordinary things, adopting the Gentiles who were hostile to Him, so that already from what He has accomplished for us, what has been said is also clear.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Ephesians%2FChapter%25203.html'
source_title='Commentary on Ephesians'
