[[commentary]]
quote='''
The works of darkness and sin are fruitless, because they bring nothing other than death and shame. Therefore, one must not participate in such works, but on the contrary, expose them, that is, admonish those who do such things.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Ephesians%2FChapter%25205.html'
source_title='Commentary on Ephesians'
