[[commentary]]
quote='''
And not only to be strengthened, but much more and greater still — "that Christ may dwell in your hearts," not on the surface, but in the depths. In what way? "Through faith." For Christ dwells in faithful hearts, coming with the Father and making His abode in them, as He also foretold (Jn. 14:23). And you will attain this when you are rooted in His love and are not shaken or troubled. Thus the apostle asks two blessings for them: that they be strengthened by the Spirit and that Christ dwell in their hearts; or rather, that you, he says, be strengthened and become worthy of having Christ dwell in your hearts.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Ephesians%2FChapter%25203.html'
source_title='Commentary on Ephesians'
