[[commentary]]
quote='''
Lest they say: "why do you rebuke us so strongly (for we have violated only one commandment) and exaggerate our guilt?" – he says that this seemingly insignificant circumstance causes substantial harm. For, just as leaven, even a small amount, by itself leavens and transforms the entire lump of dough, so too circumcision, although it constitutes only one commandment, draws you into Judaism in all its fullness.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Galatians%2FChapter%25205.html'
source_title='Commentary on Galatians'
