[[commentary]]
quote='''
He explains in what sense he called such rest "a sabbath." Because, he says, we too rest from our works, just as God, having rested from His works after the creation of the world, called that day the Sabbath. For here there is much toil for the righteous as well, and struggle, and every kind of effort in virtue; but there, there is no care or moral striving, there is immeasurable delight in God. And so, what they desired to hear — namely, that they would be delivered from their present labors — that is precisely what he said, in order to gladden them.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Hebrews%2FChapter%25204.html'
source_title='Commentary on Hebrews'
