[[commentary]]
quote='''
Whoever does anything with partiality brings great disgrace upon himself as one who does not respect his fellow and, even before his fellow, himself, because the treatment of one like oneself is also directed back to the one who acts.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520James%2FChapter%25202.html'
source_title='Commentary on James'
