[[commentary]]
quote='''
What mystery does He teach them? "I," He says, "am the vine, that is, the root, and you are the branches, and My Father is the vinedresser." For whom then does the Father care? Surely for the root? No, but for the branches.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520John%2FChapter%252015.html'
source_title='Commentary on John'
