[[commentary]]
quote='''
He compares the food He gives them with manna. "I," He says, "am the bread of life, but those who ate manna died." He did not simply add the words "in the wilderness," but with the purpose of showing that the manna did not last long for the fathers — only in the wilderness — and it did not enter the promised land with them.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520John%2FChapter%25206.html'
source_title='Commentary on John'
