[[commentary]]
quote='''
Lest they should say, "Why do You tell us about this, as if we did not know? We ourselves know that humility is good," He therefore says, "If you know these things, this alone is not enough, but you are blessed when you do them." For the Jews also knew the commandments, but they are not blessed, but rather most wretched, because they did not fulfill them.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520John%2FChapter%252013.html'
source_title='Commentary on John'
