[[commentary]]
quote='''
He commands them to bring the fish they had caught, in order to show that what they were seeing was not a phantom. Here it does not say that He ate with them, but Luke says that He also ate together with them (Luke 24:30, 43). How He ate, we cannot explain, for this occurred in an extraordinary manner. Not because His nature required food, but this was an act of condescension, as proof of the resurrection.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520John%2FChapter%252021.html'
source_title='Commentary on John'
