[[commentary]]
quote='''
"Why do you ask Me? Ask those who heard." These are the words not of an arrogant man, but of one confident in the truth of his words. "Ask," He says, "these enemies, these haters, these officers who bound Me." For this is the most indisputable proof of truth, when someone brings his own enemies as witnesses to his words. And these very officers had previously testified thus: "Never has a man spoken like this Man" (Jn. 7:46).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520John%2FChapter%252018.html'
source_title='Commentary on John'
