[[commentary]]
quote='''
"That is why," He says, "you do not believe Me, because you do not hope to receive from Me any worldly pleasure." And in another sense: "You do not believe Me because you love glory from one another." For the rulers and teachers, desiring themselves only to be in glory among the people, do not accept Me, lest their glory be diminished. And the people, seeking favor from the rulers, do not wish to turn to Me, lest on account of Me they lose honor with the rulers.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520John%2FChapter%25205.html'
source_title='Commentary on John'
