[[commentary]]
quote='''
The Jews surrounded Him and, seemingly out of a certain zeal for Him and a desire to learn the truth, asked Him to tell them "whether He is the Christ"; but in reality their question was idle and malicious. For while His works proved that He is the Christ, they demanded words for persuasion. This is more characteristic of pranksters and mockers. Nevertheless, their question, full of ingratitude and pretense, reveals their corruption.
They say: "Tell us plainly." Yet He had said so plainly many times when He came to the feasts, and He said nothing in secret, calling Himself the Son of God and the Light, and the Way, and the Door, and appealing to the testimony of Moses.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520John%2FChapter%252010.html'
source_title='Commentary on John'
