[[commentary]]
quote='''
Our Lord, knowing that the woman of Samaria was bringing the whole town out to Him, tells His disciples, I have meat that ye know not of.

That ye know not of, i. e. know not that I call the salvation of men food; or, know not that the Samaritans are about to believe and be saved. The disciples however were in perplexity: Therefore said the disciples one to another, Hath any man brought Him ought to eat?
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520John%2FChapter%25204.html'
source_title='Catena Aurea by Aquinas'

[[commentary]]
quote='''
But the Lord, knowing that the Samaritan woman would draw almost the entire city to Him and that the Samaritans would believe in Him, says: "I have something to eat, namely, the salvation of people, because I desire this salvation as none of you desire physical food. The food that I have to eat, you, My disciples, do not know. You are still carnal and cannot understand what I say in a veiled manner, and therefore you do not know that by food I mean the salvation of people." And in another sense: "You do not know this food, for you do not know that the Samaritans will believe in Me and be saved."
Calling the salvation of people His food, the Lord teaches the disciples so that they too, when they are ordained as teachers of the universe, would not concern themselves much with bodily food, but would devote all their zeal to the salvation of people.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520John%2FChapter%25204.html'
source_title='Commentary on John'
