[[commentary]]
quote='''
Wishing to show them that from Him as God the thoughts of their hearts are in no way hidden, He says: "Does this offend you?"
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520John%2FChapter%25206.html'
source_title='Commentary on John'
