[[commentary]]
quote='''
The Virgin, having heard from the Angel that Elizabeth had conceived, hastened to her, partly rejoicing in the good fortune of her kinswoman, and partly, as one most prudent, wishing to confirm conclusively whether what had appeared to her was true, so that by the truthfulness of what was said about Elizabeth she might not doubt what concerned herself. For although she hoped, she nevertheless feared lest she might somehow be deceived, and this was not from unbelief, but from a desire to know the matter more precisely. Zachariah lived in the hill country; therefore the Virgin hastens there.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%25201.html'
source_title='Commentary on Luke'

[[commentary]]
quote='''
She went into the mountains, because Zacharias dwelt there. As it follows, To a city of Juda, and entered into the house of Zacharias. Learn, O holy women, the attention which ye ought to show for your kinswomen with child. For Mary, who before dwelt alone in the secret of her chamber, neither virgin modesty caused to shrink from the public gaze, nor the rugged mountains from pursuing her purpose, nor the tediousness of the journey from performing her duty.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%25201.html'
source_title='Catena Aurea by Aquinas'
