[[commentary]]
quote='''
See what precision there is in the words. The Lord did not say "ask" and it will be given to you, but "keep asking," that is, seek unceasingly.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%252011.html'
source_title='Commentary on Luke'
