[[commentary]]
quote='''
Zechariah, being unable to make known to them by signs, asks for a tablet; and when regarding the name of the child he was found to be in complete agreement with his wife, "all marveled," for this name was not in their kinship, and no one could say that the two of them had agreed upon this beforehand.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%25201.html'
source_title='Commentary on Luke'
