[[commentary]]
quote='''
There was a sacred treasury, contributed by the God-loving, which was used for repairs and restorations in the temple, and in general for the adornment of the temple and for the sustenance of the poor. But in recent times the priests converted even this treasury to commercial dealings, dividing it among themselves, rather than using it for the purpose for which it was originally designated.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%252021.html'
source_title='Commentary on Luke'
