[[commentary]]
quote='''
And "the drachma," that is, the royal image, "was found," and there was joy both for Christ Himself who found it and for the Heavenly Powers, who are His friends and neighbors: "friends," since they do His will; "neighbors," since they are bodiless. And I would ask, are not all the Heavenly Powers His friends, while the neighbors are the nearest of them, such as thrones, cherubim, and seraphim? For pay attention to the expression: "she calls together her friends and neighbors." It evidently points to two distinct things, although this may not seem particularly important.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%252015.html'
source_title='Commentary on Luke'
