[[commentary]]
quote='''
"The axe" is the divine judgment that uproots the unworthy from among the living. If, he says, you do not repent, you will be deprived of life. The axe lies "at the root of your trees." By "root" is meant life, as we have said. But by "root" one can also understand kinship with Abraham. From this kinship with Abraham, according to the apostle (Rom. 11:21–22), those who are unworthy to be his branches are cut off. The punishment is twofold, for the sinful and fruitless one is not only cut off from kinship with the righteous, but is also cast into fire.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%25203.html'
source_title='Commentary on Luke'
