[[commentary]]
quote='''
He likewise "filled the hungry with good things" — the same ones, that is, the Gentiles (for they had no Scriptures, law, or commandments) — with good things from the Scriptures, while the Jews, who were "rich" in the law and commandments, He sent away outside Jerusalem, both the heavenly and the earthly, deprived of every good thing. For the Jews now have nothing, even though they seem to have something.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%25201.html'
source_title='Commentary on Luke'
