[[commentary]]
quote='''
He persuades the soldiers not to plunder, but to be content with their wages, that is, the pay ordinarily given by the king. Notice how John persuades the common class of people, as being without malice, to do something good, that is, to share with others, while the tax collectors and soldiers he persuades to refrain from evil. For these were not yet capable, they could not accomplish anything good, and it was sufficient for them not to do evil.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%25203.html'
source_title='Commentary on Luke'
