[[commentary]]
quote='''
Some say that one of these two was Luke himself, which is why the evangelist concealed his name.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%252024.html'
source_title='Commentary on Luke'
