[[commentary]]
quote='''
Teach us to ask for "bread" only "daily," that is, useful for our existence and for the sustenance of life, by no means superfluous, but necessary.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%252011.html'
source_title='Commentary on Luke'
