[[commentary]]
quote='''
Tears bring consolation not to those who suffer willingly, but to those who suffer unwillingly. Therefore He forbids them to weep for Him, and urges them to turn their attention to the future calamities and to weep over those calamities, when women without pity will boil their own children, and the womb that bore them will, sadly, receive back into itself that which was born from it.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%252023.html'
source_title='Commentary on Luke'
