[[commentary]]
quote='''
Many, He says, think that those who die for the truth are abandoned by God; but do not think so. You will die not because you will supposedly be abandoned by Me. For if not one of the sparrows, which are sold cheaply, is forgotten by God, how much more should your death not be forgotten, My friends, as though I do not care for you.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%252012.html'
source_title='Commentary on Luke'
