[[commentary]]
quote='''
He points to the birds in order to shame us all the more. He could have brought forward as an example the holy prophets, such as Elijah and Moses, but for greater reproach He points to the birds. Then He presents yet another reason.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%252012.html'
source_title='Commentary on Luke'
