[[commentary]]
quote='''
But Peter objects; and for this he hears the following: "before the cock crows twice, you will deny Me three times." It happened thus: immediately after Peter denied the first time, the cock crowed; then, when Peter denied the second and third time, the cock crowed again. This is what the words mean: "before the cock crows twice, you will deny Me three times."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Mark%2FChapter%252014.html'
source_title='Commentary on Mark'
