[[commentary]]
quote='''
What the Lord says here means the following: people who sin in all other matters can still make some excuse and receive forgiveness, through God's condescension to human weakness. For example, those who called the Lord a glutton and a drunkard, a friend of tax collectors and sinners, will receive forgiveness for this.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Mark%2FChapter%25203.html'
source_title='Commentary on Mark'
