[[commentary]]
quote='''
Therefore the Lord did not say, "I have saved you," but "your faith has saved you; go in peace," that is, in rest. The meaning of these words is this: be at peace, you who until now have been in sorrow and distress.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Mark%2FChapter%25205.html'
source_title='Commentary on Mark'
