[[commentary]]
quote='''
Matthew says that there were two demoniacs (Mt. 8:32), while Mark and Luke (Lk. 8:26–33) speak of one. These latter chose the more fierce of them and narrate about him. The demoniac goes and confesses Christ as the Son of God. Since those who were on the ship were uncertain about who He was, the most reliable testimony about Him follows from His enemies, I mean the demons.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Mark%2FChapter%25205.html'
source_title='Commentary on Mark'
