[[commentary]]
quote='''
He refutes the hateful Jews with irrefutable examples. How is it possible, he says, for a demon to cast out demons, when even in ordinary houses we see that as long as those living in them are at peace, the houses stand well, but as soon as division occurs in them, they fall?
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Mark%2FChapter%25203.html'
source_title='Commentary on Mark'
