[[commentary]]
quote='''
Christ foretells to the disciples that they too will be scandalized. And lest they consider this an open reproach directed at all of them, He cites the testimony of the prophet Zechariah, that they will be "scattered" (Zech. 13:7). "I will strike the shepherd" — this is spoken by God the Father. Since He permitted the Son to be struck, it is said that He struck the One who was struck by His permission. And He called the apostles "sheep" as people who are guileless.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Mark%2FChapter%252014.html'
source_title='Commentary on Mark'
