[[commentary]]
quote='''
See how powerful the passion of carnal love is! Here is Herod, who had so much respect and fear for John, yet disregarded this in order only to satisfy his passion.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Mark%2FChapter%25206.html'
source_title='Commentary on Mark'
