[[commentary]]
quote='''
"And hearing this," he says, "His relatives" — perhaps people from the same hometown as Him, or even His brothers — "went out to take hold of Him; for they said that He was out of His mind," that is, that He had a demon. Since they heard that He was casting out demons and healing diseases, out of envy they thought that He had a demon and "was out of His mind," which is why they wanted to seize Him, so as to bind Him as one possessed. This is what His relatives thought and intended to do with Him.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Mark%2FChapter%25203.html'
source_title='Commentary on Mark'

[[commentary]]
quote='''
That is, He has a devil and is mad, and therefore they wished to lay hold upon Him, that they might shut Him up as one who had a devil. And even His friends wished to do this, that is, His relations, perchance His countrymen, or His brethren. 1But it was a silly insanity in them, to conceive that the Worker of such great miracles of Divine Wisdom had become mad.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Mark%2FChapter%25203.html'
source_title='Catena Aurea by Aquinas'
