[[commentary]]
quote='''
Christ touches him as a sign that nothing is unclean. The Law forbade touching a leper as unclean; but the Savior, wishing to show that nothing is unclean by nature, that the requirements of the Law must be abolished, and that they have power only over men, touches the leper — whereas even Elisha so feared the Law that he did not even wish to see Naaman, who was leprous and asking for healing.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Mark%2FChapter%25201.html'
source_title='Commentary on Mark'
