[[commentary]]
quote='''
The evangelist calls diseases "plagues," for diseases truly contribute much to our correction, so that God punishes us with these plagues, as a father does his children.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Mark%2FChapter%25203.html'
source_title='Commentary on Mark'
