[[commentary]]
quote='''
In the figurative sense, the right hand is withered in everyone who does not perform the works of the right side. To such a person Christ says: "Rise up," that is, depart from sin; "stand in the midst," that is, in the midst of the virtues, since every virtue is a mean, inclining neither toward deficiency nor toward excess. So when he stands in this middle, then his hand will again become healthy.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Mark%2FChapter%25203.html'
source_title='Commentary on Mark'
