[[commentary]]
quote='''
The evangelist calls the first day of unleavened bread the Thursday which immediately preceded the feast of unleavened bread, for the Jews began to eat unleavened bread on Friday. The disciples approach and ask where they should eat the Passover. From this it is evident that neither Christ had His own dwelling, nor did the disciples have their own homes; for if they had, they would have received Him into them.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Mark%2FChapter%252014.html'
source_title='Commentary on Mark'
