[[commentary]]
quote='''
Then the Lord, turning every accusation upon their own head, defends Moses by saying, "Moses did not set this law in contradiction to God, but rather he addressed this law to your depravity, so that when you in your licentiousness desired to come together with other women, you would not put to death your first wife." For the Israelites, being cruel, would have murdered their wives if they were constrained to keep them. So Moses provided in the law for a writ of divorce to be given to those wives who were hated by their husbands.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Matthew.html'
source_title='Commentary on Matthew'
