[[commentary]]
quote='''
This means, if it is by divine power that I cast out demons, then I am the Son of God, and I have come for your sake, to do good to you. So, then, I have come unto you, and this is the kingdom of God. Why do you slander My coming which is for your sake?
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Matthew.html'
source_title='Commentary on Matthew'
