[[commentary]]
quote='''
He neither bids them nor impels them towards their plan to kill Him when He says, "Fill ye up also the measure of your fathers." Rather, this is what He means: since you are serpents and the offspring of such fathers, and have been plunged into such malice that you are incurable, in a short time you will be eager to outdo your fathers when you kill Me. For you shall have attained to the ultimate degree of malice when you fulfill and complete the bloodletting which your fathers omitted. Being such, how shall you escape eternal torments?
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Matthew.html'
source_title='Commentary on Matthew'
