[[commentary]]
quote='''
"Do men gather grapes from thorns, or figs from thistles? Even so, every good tree bringeth forth good fruit; but a corrupt tree bringeth forth evil fruit." The hypocrites are called thorns and thistles: they are like thorns in that they prick unexpectedly; they are like thistles in their cunning and deviousness. The corrupt tree is anyone who has been corrupted by a pleasure-loving and dissolute life.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Matthew.html'
source_title='Commentary on Matthew'
