[[commentary]]
quote='''
Jesus stayed for some time in Gennesaret, and the people recognized Him not only by sight but by the signs which He worked, and they showed fervent faith.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Matthew.html'
source_title='Commentary on Matthew'
