[[commentary]]
quote='''
Jonah, He says, after he left the belly of the whale, preached and was believed. But you will not believe Me even after My Resurrection. Wherefore you will be condemned by the Ninevites, who believed in My servant Jonah without any signs, and, what is more, were barbarians. But you who were nourished on the prophets and have seen signs, have not believed in Me, the Master. For this is what is meant by "Behold, a greater than Jonah is here."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Matthew.html'
source_title='Commentary on Matthew'
