[[commentary]]
quote='''
The young man saith unto Him, All these things have I kept from my youth up: what lack I yet? Some accuse him of boasting and arrogance. For how could he have achieved love for neighbor if he were rich? For no one who loves his neighbor as himself is wealthier than his neighbor. Others understand it thus: suppose, he says, that I have kept all these things - what do I still lack?
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Matthew.html'
source_title='Commentary on Matthew'
