[[commentary]]
quote='''
But after a long time he who bestowed the silver talent returns. The silver talent may be in the form of a silver tongue, the gift of eloquence, for the eloquence of God is as silver that is tried by fire. Or, the silver talent may be any gift that makes one brilliant and glorious. He comes and demands a reckoning from those who received.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Matthew.html'
source_title='Commentary on Matthew'
