[[commentary]]
quote='''
Every deed, be it good or evil, is called the food of the soul. And the soul, too, has teeth, but they are spiritual in nature. Then the corrupted soul will gnash its teeth, that is, grind together its now impotent faculties of action, because it practiced such things.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Matthew.html'
source_title='Commentary on Matthew'
