[[commentary]]
quote='''
That is, others out of love both for God and for me preach the Gospel, knowing that I must give an account of my preaching, and for this reason they assist me in this work. For if many join my preaching, it will be easy for me to defend the Gospel. In this way they assist me, teaching many.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Philippians%2FChapter%25201.html'
source_title='Commentary on Philippians'
