[[commentary]]
quote='''
He says this excellently, writing with spiritual grace and as if saying: for greater assurance that I will pay the debt, my own handwritten letter serves as guarantee.

Lest it seem reproachful to Philemon that the apostle, as though not trusting him, does not simply ask him concerning the slave-thief, but also gives a written guarantee in his own hand — for this would signal that Philemon is hard-hearted and inattentive to his teacher — the apostle (by the words cited) gives him to understand that he trusts him, and greatly so. For not only with your own possessions, he says, but beyond that, you owe me even your very self.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Philemon%2FPhilemon.html'
source_title='Commentary on Philemon'
