[[commentary]]
quote='''
Having explained what grace is, that is, that it is a gift of God apart from works, he says that the Israelites, seeking righteousness, did not obtain it, because they sought it poorly and from works, by which it is impossible to obtain it. "But the elect obtained it." By the word "obtained" he shows the greatness of the blessings and that everything is the work of God's grace. And in ordinary conversation we too say: he obtained a profit, that is, he acquired a gain without labor.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Romans%2FChapter%252011.html'
source_title='Commentary on Romans'
