[[commentary]]
quote='''
If he was justified by works, then he "has something to boast about, but not before God," that is, he can boast that he accomplished something well by his own labors, but this does not mean boasting before God, and is not directed toward God.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Romans%2FChapter%25204.html'
source_title='Commentary on Romans'
