[[commentary]]
quote='''
This praise is greater than the previous one; it is even the cause of it and contains it within itself: for whoever is a fellow worker is also beloved. And he crowns this one with the same.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Romans%2FChapter%252016.html'
source_title='Commentary on Romans'
