[[commentary]]
quote='''
Those who have given themselves over, he says, to the immoderate slavery of the flesh always think about fleshly things and never contemplate the divine, but those who have wholly submitted themselves to the Spirit both think and do everything spiritual.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Romans%2FChapter%25208.html'
source_title='Commentary on Romans'
