[[commentary]]
quote='''
But the mercy shown to you will also be their mercy: they will emulate you and believe, and thus will be deemed worthy of your mercy.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Romans%2FChapter%252011.html'
source_title='Commentary on Romans'
