[[commentary]]
quote='''
God is not a partial God, so as to save only you and not every person. Here he also shames the Jews and greatly frightens them as fighters against God, if they do not admit that the Gentiles are saved through faith; for they do not believe that He is the God of all and equally provides for all.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Romans%2FChapter%25203.html'
source_title='Commentary on Romans'
