[[commentary]]
quote='''
Since it seemed incredible that a gentile who had not heard the law and the prophets should be deemed worthy of honor, he proves this by the fact that God is no respecter of persons. God, he says, does not take into account persons, but examines deeds. If by deeds there is no difference between a Jew and a gentile, then nothing prevents the latter from being deemed worthy of the same honor as the former. Therefore, now that the law has been abolished, do not boast, O Jew, before the one who, being from the gentiles and doing good, was equal to you even at the time when your Judaism was in its glory.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Romans%2FChapter%25202.html'
source_title='Commentary on Romans'
