[[commentary]]
quote='''
Having said much that was harsh above, he finally heals the wounds he inflicted. He did not say: I have heard, but: "I myself am convinced," he who was reproaching and accusing you, "that you also are full of goodness," that is, of good disposition and brotherly love, though perhaps he calls goodness the fullness of virtue. He also did not say: you have goodness, but: "full." And since there is no benefit in having only goodness while not knowing how to make use of it, he added: "and are able to instruct one another," not only to learn, but even more — to teach others.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Romans%2FChapter%252015.html'
source_title='Commentary on Romans'
