[[commentary]]
quote='''
If he leads a life free from reproach, if no one reproaches him for his way of life. For if the light, He says, is darkness, then the darkness how much more?

To shut the mouths of heretics who condemned marriage, he accepts a married man into the episcopacy. For marriage is so honorable that with it one can even ascend to the sacred throne. But to restrain the incontinent, he says: "the husband of one wife." For he who preserved no affection for his deceased wife, how will he be a good leader in the Church? A bishop must be blameless. But a man twice married is not blameless, even though this is permitted by civil laws.

Who has not raised his own children, how will he manage others? It is clear that if he had first raised his children well and with care, they would not have turned out disobedient. For sins are not such by their nature that they could be stronger than such diligence. The Apostle did not say simply: not profligate children, but even entirely free from reproach of profligacy and free from evil suspicion.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Titus%2FChapter%25201.html'
source_title='Commentary on Titus'
