[[commentary]]
quote='''
He appointed the elders as teachers for the younger, women for women; for the "young men" – Titus himself, a man for men: everywhere he observes propriety. In what, then, should they be instructed and admonished? "To be self-controlled," for in youth the fire of shameful pleasures causes the most harm, which must be extinguished, and one must strive "to be self-controlled."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Titus%2FChapter%25202.html'
source_title='Commentary on Titus'
