[[commentary]]
quote='''
Everywhere the apostle desires that believers "submit to authorities." And he shows in what manner to "submit," namely, if they "are ready for every good work." From this it is clear that whoever is ready for evil does not submit to the authorities. Or, let them "be ready to incline toward the good," and not toward impiety, or anything else harmful to the soul.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Titus%2FChapter%25203.html'
source_title='Commentary on Titus'
