[[commentary]]
quote='''
But as yet they were not so, nay, being stirred up with fervid zeal, they wished to bring down fire from heaven upon them. It follows, And when his disciples James and John saw this, they said, Lord, will thou that we command fire to come down from heaven, &c.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%25209.html'
source_title='Catena Aurea by Aquinas'
