[[commentary]]
quote='''
(ubi sup.) But it seems to have been especially and wonderfully ordained that they should not seek His assistance when first the storm began to affect the boat, but after the danger had increased, in order that the power of the Divine Majesty might be made more manifest. Hence it is said, And they were filled with water, and were in jeopardy. This indeed our Lord allowed for the sake of trial, that having confessed their danger they should acknowledge the greatness of the miracle.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%25208.html'
source_title='Catena Aurea by Aquinas'
