[[commentary]]
quote='''
And being well skilled in the divine laws, he will say to him as Moses said to God, "Yet now, if thou wilt forgive their sin;—and if not, slay me together with them." For such are the bowels of the saints, that they think death with their children sweeter than life without them. He will also make the special season his advocate and shelter himself behind the sacred festival of the Passover; and will remind the Emperor of the season when Christ remitted the sins of the whole world. He will exhort him to imitate his Lord.
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Chrysostom%2FHomilies%2FConcerning%2520the%2520Statues%2FHomily%25203.html'
source_title="HOMILIES CONCERNING THE STATUES 3.2"
