[[commentary]]
quote='''
Afterwards, intending to speak of the oaths and treaties, "He took," saith he, "of the seed of the land, and planted it in a fruitful field, that it might take root by great waters. He placed it to be looked upon; and it grew, and became a weak vine, and of small stature, and it stretched out its branches towards him, and its roots were under him." Here he calls the city of Jerusalem a vine; but in saying that it stretched out its branches towards the eagle, and that its roots were under him, he refers to the treaties and alliances made with him; and that it cast itself upon him.
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Chrysostom%2FHomilies%2FConcerning%2520the%2520Statues%2FHomily%252019.html'
source_title="HOMILIES CONCERNING THE STATUES 19:9"
