[[commentary]]
quote='''
What then? He Himself speaks nothing, nor Moses, nor Elias, but He that is greater than all, and more worthy of belief, the Father, uttereth a voice out of the cloud. Wherefore out of the cloud? Thus doth God ever appear. "For a cloud and darkness are round about Him;" and, "He sitteth on a light cloud;" and again, "Who maketh clouds His chariot;" and, "A cloud received Him out of their sight;" and, "As the Son of Man coming in the clouds." In order then that they might believe that the voice proceeds from God, it comes from thence. And the cloud was bright.
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Chrysostom%2FHomilies%2FOn%2520Matthew%2FHomily%252056.html'
source_title="Homily 56 on the Gospel of Matthew"


[[commentary]]
quote='''
That it was Jesus himself [at the ascension] they knew from the fact that he had been conversing with them (for had they seen only from a distance, they could not have recognized him by sight), but that he is taken up into heaven the angels themselves inform them. Observe how it is ordered, that not all is done by the Spirit, but the eyes also do their part. But why did "a cloud receive him"? This too was a sure sign that he went up to heaven. Not fire, as in the case of Elijah, nor fiery chariot, but "a cloud received him"; which was a symbol of heaven, as the prophet says, "Who makes the clouds his chariot"; it is of the Father himself that this is said. Therefore he says, "on a cloud"; in the symbol, he would say, of the divine power, for no other power is seen to appear on a cloud. For hear again what another prophet says: "The Lord sits upon a light cloud."
'''
source_url='https://www.newadvent.org/fathers/210102.htm'
source_title="Homily 2 on the Acts of the Apostles"
