[[commentary]]
quote='''
(Hom. lxxxv) Observe how the weaker sex is the stronger; standing by the cross when the disciples fly.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520John%2FChapter%252019.html'
source_title='Catena Aurea by Aquinas'

[[commentary]]
quote='''
But the women stood by the Cross, and the weaker sex then appeared the manlier; so entirely henceforth were all things transformed.
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Chrysostom%2FHomilies%2FOn%2520John%2FHomily%252085.html'
source_title='Homily on the Gospel of John 85'
