[[commentary]]
quote='''
"Rejoice greatly, daughter of Zion"? Because all their kings had for the most part been an unjust and covetous kind of men, and had given them over to their enemies, and had perverted the people, and made them subject to their foes; "Be of good courage," It saith, "this is not such an one, but meek and gentle"; as is shown by the ass, for He entered not with an army in His train, but having an ass alone.
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Chrysostom%2FHomilies%2FOn%2520John%2FHomily%252066.html'
source_title='Homily on the Gospel of John 66'

[[commentary]]
quote='''
And this He did, figuring one prophecy and fulfilling another; and the same act was the beginning of the one and the end of the other. For the, "Rejoice, for thy King cometh unto thee meek," belonged to Him as fulfilling a prophecy, but the sitting upon an ass was the act of one prefiguring a future event, that He was about to have the impure race of the Gentiles subject to Him.
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Chrysostom%2FHomilies%2FOn%2520John%2FHomily%252066.html'
source_title='Homily on the Gospel of John 66'

[[commentary]]
quote='''
But how say the others, that He sent disciples, and said, "Loose the ass and the colt," while John saith nothing of the kind, but that "having found a young ass, He sat upon it"? Because it is likely that both circumstances took place, and that He after the ass was loosed, while the disciples were bringing it, found the colt, and sat upon it.
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Chrysostom%2FHomilies%2FOn%2520John%2FHomily%252066.html'
source_title='Homily on the Gospel of John 66'
