[[commentary]]
quote='''
(Hom. l. 1) Which is impossible: for He that sent Me is true, and therefore He that is sent must be true likewise. He every where attributes the knowledge of the Father to Himself, as being from the Father: thus here, But I know Him, for I am from Him.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520John%2FChapter%25207.html'
source_title='Catena Aurea by Aquinas'

[[commentary]]
quote='''
"I know Him," He saith, "for I am from Him, and He hath sent Me." Seest thou how He continually seeketh to prove the, "I am not come of Myself," and, "He that sent Me is true," striving not to be thought an enemy of God? And observe how great is the profit of the humility of His words.
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Chrysostom%2FHomilies%2FOn%2520John%2FHomily%252050.html'
source_title='Homily on the Gospel of John 50'
