[[commentary]]
quote='''
And what follows also indicates, that of themselves it was said, and of their traditions. Thus He added, "They are blind leaders of the blind." Whereas, had He spoken it of the law, He would have said, "It is a blind leader of the blind." But not so did He speak, but, "They are blind leaders of the blind:" freeing it from the blame, and bringing it all round upon them.

Then to sever the people also from them, as being on the point of falling into a pit by their means, He saith, "If the blind lead the blind, both shall fall into the ditch."

It is a great evil merely to be blind, but to be in such a case and have none to lead him, nay, to occupy the place of a guide, is a double and triple ground of censure. For if it be a dangerous thing for the blind man not to have a guide, much more so that he should even desire to be guide to another.
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Chrysostom%2FHomilies%2FOn%2520Matthew%2FHomily%252051.html'
source_title='Homily on the Gospel of Matthew 51'
