[[commentary]]
quote='''
Whence He puts this question, showing that nothing had been omitted that ought to be done for their salvation, saying, To whom shall I liken this generation?

You should not be surprised at His using trite instances, such as that respecting the children; for He spoke to the weakness of His hearers; as Ezekiel spoke many things adapted to the Jews, but unworthy of the greatness of God.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Matthew%2FChapter%252011.html'
source_title="Catena Aurea by Aquinas"
