[[commentary]]
quote='''
And again Paul also taught concerning this simplicity that we should not only make use of it towards God, and towards each other, but he also commandeth the servants of this world to honour their masters in simplicity, without deceit and without cunning. "Servants, be obedient to your masters in all things, not with eye-service as those who please the children of men, but with fear and trembling, and with the simpleness of heart as unto Christ."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Philoxenus%2520of%2520Mabbug%2F13%2520Ascetic%2520Discourses%2FDiscourse%25204%2520--%2520On%2520Faith-%2520First%2520Discourse%2520on%2520Simplicity.html'
source_title="13 Ascetic Discourses, Discourse 4 -- On Faith: First Discourse on Simplicity"
