[[commentary]]
quote='''
And concerning Jonah it is also written, "He feared before the Lord and fled to Joppa." For although his fear was born of simplicity, yet like a man who feared God he fled in order that he might not draw nigh to the work which he thought was too hard for his strength.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Philoxenus%2520of%2520Mabbug%2F13%2520Ascetic%2520Discourses%2FDiscourse%25207%2520--%2520Second%2520Discourse%2520on%2520the%2520Fear%2520of%2520God.html'
source_title="13 Ascetic Discourses, Discourse 7 -- Second Discourse on the Fear of God"
