[[commentary]]
quote='''
And to the Colossians, among other things, he says: “From whom the whole body, supplied and knit together, grows with a growth from God” (Col. 2:19). If we take this according to the sound of the words, it does not fit: for God does not lack anything, so as to make growth through us. But when we return to the author of our life and confess him, the Godhead, by gaining us for salvation, makes growth in us; therefore, in those who depart from him there is loss. This, then, is not to be whole, which is also to suffer loss.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Ambrosiaster%2FQuestions%2520on%2520the%2520Old%2520and%2520New%2520Testaments.html'
source_title="QUESTIONS ON THE OLD AND NEW TESTAMENTS, QUESTION 49: WHOSE SPIRIT IS TO BE SAVED"
