[[commentary]]
quote='''
The benefit of both the Father and the Son reveals the upliftment of the human race. It does not indicate a lesser Son when it calls him our Lord, nor a greater Father when it calls him our God. Because the Father will not be a true God unless he is also Lord, and the Son will not be a true Lord unless he is also God.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Ambrosiaster%2FCommentary%2520on%2520Galatians.html'
source_title="Commentary on Galatians"
