[[commentary]]
quote='''
Paul says that it is time for us to advance toward merit. That is, to rise from sleep and do good, as in the day, that is, openly; for illegal things are done at night, that is, in secret. For now, having been placed in the light of revealing, which is in the knowledge of God, and recognizing what we ought to follow, we must strive to live purely and attain the promised reward, having shaken off sleep, that is, ignorance or negligence. It is clear that, after baptism, those who live well and devote themselves to love are not far from the merit of the promised resurrection. For the good life of a Christian is a sign of future salvation.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Ambrosiaster%2FCommentary%2520on%2520Romans.html'
source_title="COMMENTARY ON ROMANS"
