[[commentary]]
quote='''
Since he shows that the one who does wicked deeds, and the one who consents to those who do them, are deserving of death, lest perhaps someone here who does this, and does not approve of those who do it, might think they can excuse themselves, he teaches that such a person will be without excuse. For it is not just that liberty be granted to him; because through hypocrisy he presents himself as not such a one, while he is found to be worse. For he deceives, so that while he ought to be punished, he appears worthy of honor.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Ambrosiaster%2FCommentary%2520on%2520Romans.html'
source_title="COMMENTARY ON ROMANS"
