[[commentary]]
quote='''
Job wants to find relief before he has to go from where he cannot return. Therefore, he does not pray for himself, but to teach the friends who think that those who suffer hardship are evil but those who are free from hardship are righteous. He desired that they should gain certainty regarding the divine resolutions about him. One should not assume that Job denies the resurrection of the dead. Rather, Job says, “From where I will not return to lead a mortal life.” Job knows that he will rise as immortal.
'''
source_url=''
source_title="COMMENTARY ON JOB 10:18-22"
