[[commentary]]
quote='''
In regard to the third, that they may attain to the end of laying up riches; hence he says, to lay up in store for themselves a good foundation against the things to come. The spiritual treasure is a storehouse of merits, which are the foundation of a future edifice prepared for us in heaven; because the entire preparation for future glory is through merits, which are acquired by grace, the principle of meriting: lay up to yourselves treasures in heaven, where neither the rust nor the moth consumes (Matt 6:20); so run that you may obtain (1 Cor 9:24).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%25201%2520Timothy.html'
source_title='Commentary on 1 Timothy'
