[[commentary]]
quote='''
Understand what I say: he explains what he had said, following Christ's method of explaining his parable: he that has ears to hear let him hear (Matt 13:9). As if to say: reduce these to a spiritual meaning: for there is a need of understanding in a vision (Dan 10:1).

As if someone were to say: you say: take a stipend, Timothy; but you do not do so, because you wish to live by the labor of your own hands. Hence, understand what I say, because discretion is necessary: for you must not take from those sources which can be an occasion of charging the Gospel with avarice either because of covetousness or laziness. But you will be able to understand this, for the Lord will give you in all things understanding: let his unction teach you of all things (1 John 2:27).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%25202%2520Timothy.html'
source_title='Commentary on 2 Timothy'
