[[commentary]]
quote='''
Since someone might ask: Are all things eternal? the Apostle says in answer: No! He is before all, that is, before all times and other things: "The Lord possessed me in the beginning of his ways, before he made anything from the beginning" (Prov 8:22). Or, He is before all in dignity: "Who among the heavenly beings is like the Lord?" (Ps 89:6).

As relating to the conservation of things he says, and in him all things hold together, that is, they are conserved. For God is to things as the sun is to the moon, which loses its light when the sun leaves. And so, if God took his power away from us, all things would immediately cease to exist: "Upholding the universe by his word of power" (Heb 1:3).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Colossians.html'
source_title='Commentary on Colossians'
