[[commentary]]
quote='''
The most inveterate pagans, being once converted, entirely alter their manners, Osee ii. 18. (George Haydock) earth is filled with the knowledge: Thus we see that since the Incarnation of Christ men have been instructed more evidently and surely in the knowledge of God.
'''

[[commentary]]
quote='''
373. Second, he sets out inability to hurt them: they shall not hurt; in my holy mountain, that is, the Church, except the willing: behold, I have given you power (Luke 10:19); and these signs shall follow them that believe: they shall speak with new tongues. They shall take up serpents: and if they shall drink any deadly thing, it shall not hurt them (Mark 16:17–18).

374. Third, he sets out the cause of both: for the earth is filled with the knowledge of the Lord: their sound has gone forth into all the earth (Ps 18:5[19:4]); I, wisdom, have poured out rivers (Sir 24:40).

The Jews explain all of this literally. Others say that it signifies that, in the times of the good kings, all the young boldly committed themselves to those who were previously plunderers and cruel men.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
