[[commentary]]
quote='''
He sets out the diversity of wills: the spirit, that is, the will, shall be broken, that is, divided, in the bowels thereof, that is, in the inhabitants of the land: every kingdom divided against itself shall be made desolate (Matt 12:25).

Fourth, as to the error of taking counsel from men: and I will cast down their counsel: he catches the wise in their craftiness, and disappoints the counsel of the wicked (Job 5:13); and from demons: and they shall consult, in vain, above: and when they shall say to you: seek of pythons, and of diviners, who mutter in their enchantments (Isa 8:19).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
