[[commentary]]
quote='''
379. And the envy of Ephraim shall be taken away. Here the condition of the liberated is shown,

and first, as to concord, in contrast to the hatred which had existed between Ephraim and Judah: and the envy of Ephraim shall be taken away, that is, their hatred; this was fulfilled in the return from captivity, according to the first explanation; or as to the unity of faith, according to the second; or it will be fulfilled in the future, as to the third explanation. Of this concord: the house of Judah shall go to the house of Israel, and they shall come together out of the land of the north to the land which I gave to your fathers (Jer 3:18).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
