[[commentary]]
quote='''
Thus says the Lord: what is this. Here he begins to remove the impediments to their liberation.

And first, he removes the impediments;

second, he applies the remedies: who has believed our report (ch. 53).

Concerning the first, he removes three impediments:

first, the lack of divine benefits;

second, the dejection of persons: give ear to me, you that follow (ch. 51);

third, poverty of goods: arise, arise (ch. 52).

Concerning the first, he does three things:

first, he excludes the impediment;

second, he gives himself as an example: the Lord has given (Isa 50:4);

third, he deduces salutary counsel: who is there among you that fears the Lord (Isa 50:10).

Concerning the first, he does two things:

first, he excludes the lack of divine benefits on the part of the divine will;

second, on the part of the divine power: is my hand shortened (Isa 50:2).

Concerning the first, he does three things.

First, he excludes the lack of divine will, as though of his own accord God did not wish to benefit them, excluding a twofold manner of alienation, namely, the manner of alienating a wife, which occurred through a bill of divorce, as is said in Deuteronomy 24:1, which indeed was permitted to them because of the hardness of their hearts (Matt 19:8). What is this bill of the divorce of your mother?

But, on the contrary, Jeremiah 3:8 says, because Israel had played the harlot, I had put her away.

And to this is to be said that the Lord, considered in himself, did not repudiate them, but rather they, through their sins, put God away. He also excludes the manner of alienating a possession: or who is my creditor, to whom I sold you, as if to say: if I should sell you, who are my inheritance (Isa 19:25), to him, what should I repay, not having anything else? Thus it is clear, because I did not alienate you from my dominion, that I am ready to benefit you of my own accord.

Second, he shows the sin of human will: behold you are sold for your iniquities: but I am a carnal man, sold under sin (Rom 7:14).

Note on the words, you are sold for your iniquities (Isa 50:1), that man sells many things for sins:

first, the virtue of his soul: they have given all their precious things for vile things (Lam 1:11);

second, his heavenly inheritance: the Lord be merciful to me, and not let me sell the inheritance of my fathers (1 Kgs 21:3);

third, the liberty of his soul: there is not a more wicked thing than to love money (Sir 10:10);

fourth, the honor of divine love: the Lord loves the children of Israel (Hos 3:1).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
