[[commentary]]
quote='''
"The city of your sanctuary" (sancti), that is, the sanctuary of the temple, namely, Jerusalem: "the enemy has put out his hand to all her desirable things" (Lam 1:10).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
