[[commentary]]
quote='''
Second, the praise of God: O Lord our God, other lords besides you have had dominion over us, and therefore we could not give ourselves to praise of you; only in you, to whom alone we give ourselves, having no other god: servants have ruled over us (Lam 5:8).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
