[[commentary]]
quote='''
Third, the ending of punishments as to those who are corrected: but the thrasher shall not thrash it for ever: he that ploughs, should plough in hope, and he that thrashes, in hope to receive fruit (1 Cor 9:10).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
