[[commentary]]
quote='''
Third, as to the profanation of holy things: and the covering, that is, the holy things formerly hidden, which no one but the priest was allowed to see, of Judah shall be discovered, that is, laid bare: the gentiles have seen your shame (Lam 1:8).

Fourth, as to the destruction of their armory: you shall see in that day the armory, that is, the house of the forest, in which arms were hidden, overthrown; concerning this building, see 1 Kings 7. The city of David, most strongly, or Jerusalem itself with a strong wall in many places: the tower of David, which is built with bulwarks (Song 4:3).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
