[[commentary]]
quote='''
Second, in particular: for you have reduced;

and first, works which pertain to the suppression of the wicked;

second, which pertain to the exaltation of the good: and the Lord of hosts shall make (Isa 25:6).

586. Concerning the first, he does three things:

first, he threatens the scourge of punishment;

second, he sets out the fruit of punishment: therefore shall a strong people praise you (Isa 25:3);

third, the manner of punishment, where it says, as heat in thirst (Isa 25:5).

Therefore, he first says, you have reduced the city, Jerusalem, to a heap; the house of strangers, to God, namely, the Jews; to be no more built up for ever, for it was not afterwards built in the same place, above: behold Damascus shall cease to be a city (Isa 17:1); Zion shall be ploughed as a field, and Jerusalem shall be as a heap of stones (Mic 3:12); you are brought to nothing (Ezek 27:36). Or, this refers to Babylon, or some other city of the gentiles who were opposed to them.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
