[[commentary]]
quote='''
58. He denounces the sin of the priest in two matters.

In corrupting the truth of doctrine: hence he says, your silver is turned into dross: the words of the Lord are pure words: as silver tried by the fire, purged from the earth, refined seven times (Ps 11:7[12:6]). The prophets prophesied falsehood (Jer 5:31).

Second, in relaxing the severity of discipline, which is signified by wine, for this is the wine which the Samaritan poured in (Luke 10:34); hence he says, your wine is mingled with water: woe to them that sew cushions under every elbow (Ezek 13:18).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
