[[commentary]]
quote='''
826. Hear, you deaf. Here he shows that they are hard-hearted or disobedient toward his precepts.

And first, he shows their hard-heartedness, calling them deaf and blind unitedly: for their own malice blinded them (Wis 2:21), though they may have the eyes and ears of the body, which shows that those who see take heed and those who have the ears of their hearts open obey.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
