[[commentary]]
quote='''
107. He shall answer. Here the refusal of the one elected is set out.

And first, his reasonable excuse is shown;

second, his renunciation of office is concluded where it says, make me not ruler of the people.

In excuse, he brings forward three things, namely, his impotence to repel harmful things: I am no healer, namely, that I might heal your miseries: is there no balm in Galaad? Or is there no physician there? (Jer 8:22); to supply need: and in my house there is no bread, by which I might supply the need of your hunger: the little ones have asked for bread, and there was none to break it unto them (Lam 4:4); to foster or preserve what is necessary: nor clothing, by which heat is preserved: she shall not fear for her house in the cold of snow: for all her domestics are clothed with double garments (Prov 31:21).

108. Make me not ruler of the people. Here his renunciation of office is concluded, where a threefold reason is placed, namely, the impediment of devout contemplation: can I leave my fatness, which both gods and men make use of? (Judg 9:9); of sweet affection: can I leave my sweetness? (Judg 9:11); and of spiritual exultation: can I forsake my wine, that cheers God and men, and be promoted among the other trees? (Judg 9:13).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
