[[commentary]]
quote='''
Second, he teaches the manner of seeking: let the wicked, sinning against God, forsake his way, and the unjust man, sinning against his neighbor, above: take away the evil of your devices from my eyes (Isa 1:16).

Third, he sets out the fruit of returning, namely, mercy: and let him return to the Lord, and he will have mercy on him; for he is bountiful, that is, of manifold mercy, to forgive: turn to the Lord your God: for he is gracious and merciful (Joel 2:13–14).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
