[[commentary]]
quote='''
Third, he promises the benefit of peace for the destruction of enemies: for he shall bring down them that dwell on high, the high city he shall lay low. He shall bring it down even to the ground, he shall pull it down even to the dust. The Jews say this refers to the Romans, but it can refer to any of their enemies, or, mystically, to the Jews themselves, above: the bulwarks of your high walls shall fall (Isa 25:12).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
