[[commentary]]
quote='''
221. And I said. Here the announcer of the sentence is set out.

And first, his humility is shown;

second, his purity: and one of the seraphim flew to me (Isa 6:6);

third, his authority: and I heard (Isa 6:8).

His humility shown in confession of sin. And he confesses a threefold sin.

In his speech, sin of omission: woe is me, because I have held my peace, in not denouncing Ozias the king, and thus he laments the fault; I have held my peace, from praising God, and thus he laments the harm, below: his watchmen are all blind, they are all ignorant: dumb dogs not able to bark, seeing vain things, sleeping and loving dreams (Isa 56:10). Praise is not seemly in the mouth of a sinner (Sir 15:9); sin of commission: because I am a man of unclean lips: let not your mouth be accustomed to indiscreet speech: for therein is the word of sin (Sir 23:17[13]).

Second, the sin of association with wicked men: and I dwell in the midst of a people that has unclean lips: evil communications corrupt good manners (1 Cor 15:33).

Third, the sin of presumption: I have seen with my eyes the King the Lord of hosts, as if to say: he who is impure cannot enter the Lord's temple; how much more can he not see the Lord himself? We shall certainly die, because we have seen God (Judg 13:22); and this was from reverence. But Jacob said: I have seen the Lord face to face, and my soul has been saved (Gen 32:30); and this is from confidence. Jerome: happy conscience which has sinned in speech, not by his own vice, but only of a people that has unclean lips.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
