[[commentary]]
quote='''
Put me in remembrance. Here he gives a place for a response: put me in remembrance, as if to say: consider what I have done for you, tell if you have any thing, to excuse yourself, or to accuse me, to justify yourself, that is, that you should be judged to be just: if you have any thing to say, answer me, speak: for I would have you to appear just (Job 33:32).

We ought to put God in remembrance, as to the wonders which he has done, that we should worship: remember his marvelous works which he has done (Ps 105:5); the benefits which he has given, that we should give thanks: I remembered your mercy (Sir 51:11–12); the torments he sustained, that we should feel compassion: remember my poverty (Lam 3:19); the precepts which he gave, that we should observe them: they are mindful of his commandments to do them (Ps 103:18).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
