[[commentary]]
quote='''
Fourth, as to their contempt for the just: that say, namely, to those who do not adore idols: he is grievous unto us (Wis 2:15); or that say, to God: who say to God: depart from us, we desire not the knowledge of your ways (Job 21:14). These shall be smoke. Here he threatens punishment. And first, the length of the punishment: smoke, that is, like smoke is consumed by fire, so shall they be burned by my anger: a fire is kindled in my wrath, and shall burn even to the lowest hell (Deut 32:22).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
