[[commentary]]
quote='''
Third, he sets out the multitude of the enemy: and the multitude of them that fan you, shall be like small dust: a nation come up upon my land (Joel 1:6), or the destruction of the enemy, as above: he shall be carried away as the dust of the mountains before the wind (Isa 17:13).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
