[[commentary]]
quote='''
272. For before the child know. Here the interpretation of the sign is set out; and it is already clear according to the literal interpretation. According to the other interpretation, however: for before the child know, by created knowledge, his father, his putative father Joseph, or God; the strength of Damascus, and the spoils of Samaria shall be taken away, according to this, this can also be referred to the captivity of Samaria.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
