[[commentary]]
quote='''
Because the former distresses are forgotten. Here he promises rewards seen. And first, in general, as to the removal of evils: because the former distresses are forgotten, not because of lack of knowledge, but because they have been succeeded by good things, above: you shall forget the shame of your youth (Isa 54:4).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
