[[commentary]]
quote='''
And he assigns the cause: for the Lord is our judge, judging us by our adversaries: behold your king comes to you, meek (Zech 9:9).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
