[[commentary]]
quote='''
Second, he sets out the reason for their subjection: because you were forsaken, it is just that you should be comforted after your distress; into the pride, height, of ages, through many ages. This also mystically befits the Church; after a storm you make a calm (Tob 3:22).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
