[[commentary]]
quote='''
1078. Second, as to the keeping of their possessions: and strangers shall stand. This could be fulfilled literally, as some foreigners were employed in these menial services, like the Gabaonites: so let them live, as to serve the whole multitude (Josh 9:21); or mystically: the gentile preachers, flocks: the simple believers of the Church, and these keep and cultivate the Church herself by their merits and teaching.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
