[[commentary]]
quote='''
Second, as to the temporal execution of his eternal intention: and now I have brought it to effect. Hills, princes, fighting together, fighting each other. Short of hand, that is, my hand is drawn back from their aid; or their hand was diminished from their own aid; and like the grass of the housetops: let them be as grass upon the tops of houses (Ps 128[129]:6).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
