[[commentary]]
quote='''
He shows the type of torment this is continuing, "You set up witnesses against me." For Eliphaz and his companions made a pretense of defending the justice of God and in this they wanted to stand like witnesses to speak on behalf of God and attack Job to convict him of sin. Therefore, "you multiply your anger," that is the effect of your anger when you punish me in so many different ways, "and your punishments battle against me," when they assault me with a certain authority and without contradiction. For soldiers who normally attack with royal authority and without contradiction anyone who is thought to be a criminal.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Job.html'
source_title='Commentary on Job'
