[[commentary]]
quote='''
After rain falls from the clouds, some remnants of the vapors remain behind, from which the clouds are formed. These conceal heaven from our point of view which is like the throne of God, according to the last chapter of Isaiah, "Heaven is my throne." (66:1) Expressing this he continues, "He keeps hidden the face of his throne," for he holds back as though hiding the face of heaven, which is his throne. He does this by the clouds, which prohibit us from seeing heaven, and so he says, "and he expands his cloud over it," a cloud produced by his power.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Job.html'
source_title='Commentary on Job'
