[[commentary]]
quote='''
He shows the same thing to be true for the adulterer saying, "The eye of the adulterer," who spies on the bed of another, "watches for the darkness," so that he cannot be caught, and so he says, "saying: No one will see me," that is, he watches in the dark so that he will not be seen by anyone. As if the cover of night were not enough for him, he employs still other methods of concealment, and so he says, "and he will cover his face," by changing his clothes in some way.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Job.html'
source_title='Commentary on Job'
