[[commentary]]
quote='''
His adversity partly consisted in the exterior signs of sadness, and so he uses images to show how his signs of joy had been changed. These are either musical instruments, and he expresses this alternative saying, "My lyre was turned to mourning," as if to say: Mourning had taken the place of the lyre I used to use in joy for me; or songs sung by the human voice, and so he says, "and my song," which I used to express my joy, has changed, "to the voice of those who weep."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Job.html'
source_title='Commentary on Job'
