[[commentary]]
quote='''
Because of all these good works, he was confident that his prosperity would endure. He describes the continuity of his prosperity first in his own person, and so he says, "And I said, 'I will die in my little nest,'" because I hoped from my past merits that I would quietly die in my house, not exiled from my house, nor even in a troubled house. Nor yet did he believe that he should worry about a timely death, and so he says, "like a palm tree," which lives a very long time, "I will multiply my days," in the great length of my life.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Job.html'
source_title='Commentary on Job'
