[[commentary]]
quote='''
After he showed that he was not lustful (v.1) or unjust (v.5), he shows next that he was not without pity. He first shows this from the fact that he did not take benefits away from the poor. For some men deny alms to the poor man seeking them from the beginning. He excluded this from himself saying, "If I denied the poor what they sought." Some do not refuse them but put off giving the gift. He excludes this from himself saying, "and if I made the eyes of the widow wait."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Job.html'
source_title='Commentary on Job'
