[[commentary]]
quote='''
But on the contrary sometimes men die either buried by the earth or even crushed by walls falling in an earthquake, and so he says, "their light will be withheld from the wicked," by death. Sometimes fortifications and very strong towers are cast down by an earthquake, and as to this he says, "and their upraised arm," is broken, that is, a very strong fortification or some powerful friend in whom a man confides like his own arm.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Job.html'
source_title='Commentary on Job'
