[[commentary]]
quote='''
The Evangelist, having shown us Christ's invitation to a spiritual drink, now presents the disagreement of the people. First, the disagreement among the people themselves; secondly, that of their leaders (v 45). He does two things about the first. First, he states what those who disagreed said; secondly, he states the fact that there was a disagreement (v 43).

What the people said varied according to their different opinions about Christ. And he gives three of their opinions: two of these were the opinions of those who were coming for spiritual drink; and the third was held by those who shrank from it.

The first opinion was that Christ was the Prophet. So he says, From that moment, i.e., from the time Christ had spoken on the great day of the feast, hearing these words of his, some of the people said, i.e., those who had now begun to drink that water spiritually, Truly, this is the Prophet. They did not just call him a prophet, but the Prophet, thinking that he was the one about whom Moses foretold: "The Lord your God will raise up a prophet for you from your brothers... you will listen to him" (Dt 18:15).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520John%2F7.htm'
source_title='Commentary on John'
