[[commentary]]
quote='''
2442 As to the second, he says, Behold, your mother! so that John will care for her as much as a son cares for his mother; and Mary is to love John as a mother loves her son.

2443 The Evangelist shows the obedience of the disciple when he says, and from that hour the disciple took her to his own. For Bede, this should read as his own (in suam); and so the meaning is, the disciple, John, took her, the mother of Jesus, as his own, mother. But according to Augustine, and agreeing with the Greek text, we should read it as to his own (in qua), not to his own home, for John was one of those who said, "We have left everything and followed you" (Mt 19:27); Rather, the disciple took Mary to his own guardianship, to eagerly and respectfully care for her.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520John%2F19.htm'
source_title='Commentary on John'
