[[commentary]]
quote='''
Here is viewed the effect of divine blows. It is like a livid spot on a person's body, the effect from a rod inflicting blows.

First is the weakening of powers of an entire people. For: "He has made my flesh": by which people eternally existing: and "my skin waste away": in which are delicate bones. Also: "my bones": in which are a strong warrior people. So, the Book of Baruch 3:10 says: "Why is it, O Israel, why is it that you are in the land of your enemies that you are growing old in a foreign country?"
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Lamentations.html'
source_title='Commentary on Lamentations'
