[[commentary]]
quote='''
Second, such is insofar as to threats: "The lips and thoughts of my assailants are against me all the day long." As Psalm 38:12 says: "those who seek my hurt speak of ruin, and meditate treachery all the day long."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Lamentations.html'
source_title='Commentary on Lamentations'
