[[commentary]]
quote='''
Here reference is made to the exercise of joy: "The joy of our hearts has ceased, our dancing has been turned to mourning." As the prophet Amos states: "I will turn your feasts into mourning, and all your songs into lamentations." (Amos 8:10).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Lamentations.html'
source_title='Commentary on Lamentations'
