[[commentary]]
quote='''
Here a vindicated Judah (Jerusalem) is sought. First is recalled the fault within memory. As expressed: "Let all their evil-doing come before thee." That is, from their sins. For, Psalm 109:14 exclaims: "May the iniquity of his fathers be remembered before the Lord, and let not the sin of his mother be blotted out!"

Second, a penalty is sought. As said: "and deal with them as thou hast dealt with me because of my transgressions." And, as said above in Verse 12: "which the Lord inflicted on the day of his fierce anger."

Third, a cause is assigned. As Verse 22 concludes: "for my groans are many and my heart is faint." Namely, due to the evils that I (Judah, Jerusalem), suffer from such enemies. As Jeremiah 8:18 declares: "My grief is beyond healing, my heart is sick within me."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Lamentations.html'
source_title='Commentary on Lamentations'
