[[commentary]]
quote='''
Hence they say, to what purpose is this waste? But why did they say this? They had heard the Lord greatly commend mercy; above, 19:21: if thou wilt be perfect, go sell what thou hast, and give to the poor.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Matthew.htm'
source_title='Commentary on Matthew'
