[[commentary]]
quote='''
Then the consequences of the beheading are set forth. And first the fulfillment of the promise is set forth; secondly, the burial. He says therefore and his head was brought in a dish. And in this Herod was blameworthy, because he exercised cruelty amid his pleasures: hence it is said that a certain governor loved a certain courtesan, and when she was in his lap, she said that she had never seen a man killed. And when he was at dinner, he had a man deserving of death brought forth, and had him beheaded before her: which the Romans learned, and he was banished from Rome. So this man too was sent into exile.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Matthew.htm'
source_title='Commentary on Matthew'
