[[commentary]]
quote='''
Likewise, devotion is also demonstrated, because they not only asked that he lay hands on them, but they only besought him that they might touch but the hem of his garment. By the hem is signified the least commandments, or the flesh of Christ, or the sacrament of Baptism. And as many as touched, namely through faith, were made whole. Hence Mark 16:16: he that believes and is baptized shall be saved.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Matthew.htm'
source_title='Commentary on Matthew'
