[[commentary]]
quote='''
"Again he sent other servants." Likewise, he sent prophets individually, as Moses and Aaron and others; but after, in the time of David, he sent many companies of prophets. For the Lord wills to set his mercy against their malice. Hence "and they did to them in like manner." Deut 31:27: "You have always been contentious against the Lord."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Matthew.htm'
source_title='Commentary on Matthew'
