[[commentary]]
quote='''
And when the Pharisees were gathered together, Jesus asked them. After he had responded to them, he himself wished to raise an objection: and he does two things. First, the question is presented; secondly, its effect, at no man was able to answer him a word. Concerning the first, first the question is proposed; secondly, the response; thirdly, he objects against it. He says, therefore, and when the Pharisees were gathered together, Jesus asked them. They were gathered together to tempt him; hence he poses the question.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Matthew.htm'
source_title='Commentary on Matthew'
