[[commentary]]
quote='''
Then when he says, I hope in the Lord Jesus to send Timothy to you soon, he proposes his own disciples as an example: first, Timothy and then, Epaphroditus. In regard to the first he does three things: first, he promises to send Timothy; secondly, he commends him (2:20); thirdly, he hints at the time he will send him (2:23).

He says, therefore, I hope in the Lord Jesus to send Timothy to you soon. Here it should be noted that the Apostle has such trust in God that he attributes the slightest things to God: "Not that we are sufficient of ourselves to claim anything as coming from us; our sufficiency is from God" (2 Cor. 3:5).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Philippians.html'
source_title='Commentary on Philippians'
