[[commentary]]
quote='''
Then when he says, but says the Scripture, he shows the fruit of faith on the same authority.

First, he quotes the authority;

second, he explains, at this is the word of faith;

third, he proves that the explanation is fitting, at believe in your heart.

First, therefore he says: but says the Scripture? It says this: the word is near you, even on your mouth and in your heart. For this is what follows after the aforementioned words in Deuteronomy: the word is very near you, in your mouth and in your heart (Deut 30:14).

As if to say: do not suppose that you are lacking the word of justifying faith, just because Christ is in heaven according to his divine nature and descended into hell after the death of his human nature. For in descending from heaven and rising from the dead, he impressed the word of faith on your lips and in your heart.

Hence the statement that the word is near you can be referred to the fact that we have obtained God's word through Christ's birth and resurrection: it was declared at first by the Lord (Heb 2:3); behold, I have given my words in your mouth (Jer 1:9).

Or, according to the Gloss, the word near should be understood with reference to usefulness, as we say something is near us when it is expedient or useful to us. For our heart is cleansed by the word of God: now you are clean because of the word which I have spoken to you (John 15:3).

Or it can be referred to the fact that the words of faith, even though they are above reason—many things are shown to you above the understanding of men (Sir 3:25)—are nevertheless not contrary to reason, because truth cannot be contrary to truth. Your decrees are very sure (Ps 93:5).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Romans.html'
source_title='Commentary on Romans'
