[[commentary]]
quote='''
The third pertains to those to whom he was writing: hence he adds: so that I may come to you with joy, and this by God's will, against which he wanted to do nothing: making request, if by any means now at length I may have a prosperous journey, by the will of God, to come unto you (Rom 1:10), and may be refreshed with you, i.e., that from your presence I may receive refreshment from my tribulations.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Romans.html'
source_title='Commentary on Romans'
