[[commentary]]
quote='''
After showing that we ought not remain in sin and that we have the faculty for this, the Apostle concludes with a moral exhortation.
And concerning this he does three things:
first, he proposes an admonition;
second, he assigns a reason, at for sin shall not;
third, he raises and solves a question, at what then? Shall we sin.
In regard to the first he does two things:
first, he proposes the admonition;
second, he clarifies it, at so as to obey.

First, therefore, he says: we have said that our old self was crucified once, so that the body of sin may be destroyed. This means that the power of sin has been so weakened that it cannot rule us. Let not sin therefore reign in your mortal body any longer.
He does not say: let not sin be in your mortal body, because as long as our body is mortal, i.e., bound to the necessity of death, it is not possible for sin not to be in our body, i.e., the inclination to sin. But since we have been freed from the kingdom of sin by God, we must struggle in order that sin not recover its dominion now lost in our body. And this is what he says: let not sin reign in your mortal body. This is something about which one must be on his guard, as long as we wear the mortal body: the corruptible body is a load upon the soul (Wis 9:15).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Romans.html'
source_title='Commentary on Romans'
