[[commentary]]
quote='''
After showing that the fall of the Jews is deplorable, though not entirely excusable, the Apostle now shows that it is not universal.
First, he raises a question;
second, he answers it, at God forbid;
third, he draws a conclusion, at what then.

First, therefore, he says: I say then: has God entirely cast away his people? i.e., the Jews, because he calls them unbelieving and contrary. Even the Psalmist asks: O God, why dost you cast us forever? (Ps 74:1); the Lord has scorned his altar (Lam 2:7).

Then when he says, God forbid, he answers the question and shows that God has not totally rejected the Jewish people. And this is what he says: God forbid that the Jewish people be rejected in their entirety. He proves this, first of all, with respect to himself, saying: for I also, living in the faith of Christ, am an Israelite by race: are they Israelites? So am I (2 Cor 11:22).

And because there were among the people of Israel some proselytes not descended in the flesh from the patriarchs, he says that this is not so of him, adding: of the seed of Abraham: are they descendants of Abraham? So am I (2 Cor 11:23).

Furthermore, among the Jewish people the tribes were distinguished according to the sons of Jacob, some of whom were sons of slaves and some of wives. Joseph and Benjamin were sons of Rachel, Jacob's fondest wife. Hence he shows his eminence among the Jewish people, saying: of the tribe of Benjamin: of the people of Israel, of the tribe of Benjamin (Phil 3:5). Hence, some apply to Paul what is in Genesis: Benjamin is a ravenous wolf, in the morning devouring the prey, and at evening dividing the spoil (Gen 49:27).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Romans.html'
source_title='Commentary on Romans'
