[[commentary]]
quote='''
After showing how the gentiles have been called to faith by the election of God's grace and also some of the Jews, i.e., a minority who did not stumble and fall, the Apostle now discusses in more detail the fall of the Jews.

In regard to this he does three things.

First, he explains the cause of their fall, over which he laments; from which he shows the cause of their fall to be miserable;

second, he shows that their fall is not universal, at I say then (Rom 11:1);

third, that it is neither unprofitable nor irreparable, at I say then (Rom 11:1).

In regard to the first he does two things:

first, he shows that their fall is lamentable, considering its cause;

second, that it is not wholly inexcusable, at but I say: have they not heard? (Rom 10:18).

In regard to the first he does two things:

first, he shows that he feels pity for the Jews;

second, the cause of his pity, at for I bear them witness.

First, therefore, he says: I have said that the Jews have not attained the law of justice, because they stumbled over the stumbling block. But I am not indignant against them; rather, I feel compassion. And, therefore, I say to you, brethren, whether you be converts from the gentiles or from the Jews: you are all brethren (Matt 23:8), the will of my heart is for their salvation, namely, that they be saved, as I have been saved: I wish that all were as I myself am (1 Cor 7:7); would to God that all who hear me this day might become such as I am (Acts 26:29). In this he was conformed to God, who desires all men to be saved (1 Tim 2:4).

Not only his will but his prayer is directed to their salvation, but even the affection of his will, hence, he adds: and my prayer to God is for them unto salvation: far be it from me that I should sin against the Lord by ceasing to pray for you (1 Sam 12:23); pray for one another that you may be saved (Jas 5:16).

This makes it clear that we should pray for unbelievers that they may be saved, because faith is a gift from God: by grace you have been saved through faith; and this is not your own doing, it is the gift of God (Eph 2:8).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Romans.html'
source_title='Commentary on Romans'
