[[commentary]]
quote='''
The second cause is the mutual consolation found in friendly communication. Hence he continues that I may be comforted together in you, i.e., me by seeing you and imparting a grace, and all of us by that which is common to us both, your faith and mine. For it is a source of mutual consolation to be one in the faith: but God who comforts the downcast comforted us by the coming of Titus: not only by his coming but also by the comfort with which he was comforted in you (2 Cor 6:6).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Romans.html'
source_title='Commentary on Romans'
