[[commentary]]
quote='''
The person greeted is mentioned when he says, to Titus, whom he describes from three marks: first, from his name; second, from his love; third, from his sonship.

He is a son or child through love and the faith, which should be common, so that all say the same thing. Hence he says, according to the common faith, which is also called Catholic, i.e., universal. Hence, it is said: one Lord, one faith, one baptism (Eph 4:5).

The good he wishes him is grace and peace. These usually go together, because grace is the beginning of all spiritual gifts, and peace is the end: he makes peace in your borders (Ps 147:14). From God the Father and from Christ Jesus our Savior.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Titus.html'
source_title='Commentary on Titus'
