[[commentary]]
quote='''
"Why do you persecute me as also the Lord does, and are not satisfied with my flesh? Why do you add your wrath to divine wrath without doing this according to God's will? Even though God punishes, he, nonetheless, wants to be good to us—and therefore, why do you insatiably use the harshness of your words against me?" In fact, abusive words are sufficient to devour flesh. So let us fear invectives and insults, because we are aware of the fact that they wound our brothers.
'''
source_url=''
source_title="COMMENTARY ON JOB 19:20-22"
