[[commentary]]
quote='''
And certain women who had been healed of evil spirits and infirmities, Mary, who is called Magdalene, from whom seven demons had gone out. Mary Magdalene, she is the one whose silent name the next reading relates as one who repented. For the evangelist, beautifully and reverently, when he mentions her traveling with the Lord and ministering to him from her resources, reveals her by her known name. But when he describes the sinful, yet repentant woman, he generally says "woman"; for otherwise, the name of such great fame, by which she is venerated today in all the Churches, would be stained by the mark of ancient error. Of whom it is reported that seven demons went out, showing that she was full of countless, indeed all, vices. For because the ages proceed by the seven days, the number seven often in the Scriptures signifies universality. Hence also the prophet embraces the grace of the Holy Spirit with the distinction of seven virtues.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Luke.html"
source_title = "On the Gospel of Luke"

[[commentary]]
quote='''
Mary Magdalene is the same of whose repentance, without mention of her name, we have just read. For the Evangelist, when he relates her going with our Lord, rightly distinguishes her by her known name, but when describing the sinner but penitent, He speaks of her generally as a woman; lest the mark of her former guilt should blacken a name of so great report. Out of whom seven devils are reported to have gone, that it might be shown that she was full of all vices.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%25208.html'
source_title='Catena Aurea by Aquinas'

[[commentary]]
quote='''
But Mary is by interpretation, "bitter sea," because of the loud wailing of her penitence; Magdalene, "a tower, or rather belonging to a tower," from the tower of which it is said, Thou art become my hope, my strong tower from the face of my enemy. (Ps. 61:3.)
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%25208.html'
source_title='Catena Aurea by Aquinas'
