[[commentary]]
quote='''
And Jesus rebuked the unclean spirit, and healed the boy, and gave him back to his father. He does not rebuke the boy, who was suffering the attack, but the demon which was causing it, because one who desires to correct a sinner must drive away the vice by surely reproving and hating it, but ought to restore the man with love, until he can be returned healthy to the spiritual fathers of the Church.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Luke.html"
source_title = "On the Gospel of Luke"

[[commentary]]
quote='''
While the boy is coming to our Lord, he is dashed to the ground; because men when turned to the Lord are often grievously afflicted by the devil, that he may instil a hatred of virtue, or revenge the injury of his expulsion. As in the beginning of the Church he waged as many fierce conflicts as he had to bewail losses suddenly brought upon His kingdom. But our Lord rebukes not the boy who suffered violence, but the evil spirit who inflicted it; for he who desires to correct the sinner, ought by reproof and abhorrence to drive away the vice, but to revive the man by gentleness, until he can restore him to the spiritual father of the Church.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%25209.html'
source_title='Catena Aurea by Aquinas'
