[[commentary]]
quote='''
And he was separated from them about a stone's throw. And kneeling down, he prayed, saying. Having given the apostles the command to pray, he himself, separated from them, prays alone for all, signifying that his prayer is as far removed from ours as his passion is, and he kneels to show the humility of his mind by the posture of his body. He was separated from them about a stone's throw, as if to typify for them that they should direct the stone at him, that is, that they should bring him into the temptation of the law which was inscribed on stone. For that stone can come as far as he, since Christ is the end of the law for righteousness to everyone that believes.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Luke.html"
source_title = "On the Gospel of Luke"

[[commentary]]
quote='''
He also alone prays for all, who was to suffer alone for all, signifying that His prayer is as far distant from ours as His Passion.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%252022.html'
source_title='Catena Aurea by Aquinas'
