[[commentary]]
quote='''
In the Greek language, φυλάξαι signifies to keep, and gaza in Persian means riches, hence gazophylacium is used for the name of the place in which money is kept. Now there was a chest with an opening at the top placed near the altar, on the right hand of those entering the house of God, into which the Priests cast all the money, which was given for the Lord's temple. But our Lord as He overthrows those who trade in His house, so also He remarks those who bring gifts, giving praise to the deserving, but condemning the bad. Hence it follows, And he saw also a certain poor widow casting in thither two mites.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%252021.html'
source_title='Catena Aurea by Aquinas'
