[[commentary]]
quote='''
And he said to them: These are the words which I spoke to you while I was still with you. That is, while I was still in the mortal flesh in which you also are. For then he had been resurrected in the same flesh, but was not with them in the same mortality. And indeed he was with them for forty days after he rose again (as it is read) by the exhibition of bodily presence, but he was not with them in the fellowship of human frailty.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Luke.html"
source_title = "On the Gospel of Luke"


[[commentary]]
quote='''
Because it is necessary to fulfill all things that are written in the law of Moses and the Prophets and the Psalms concerning me. See how he dispelled all doubts. He was seen, he was touched, he ate, he was indeed himself. Yet, lest he should appear to deceive human senses in any way, he directed them to the Scriptures. Let the pagans say what they will, he was a magician, he could show himself in this way. But could a magician have prophesied about himself before he was born? Produce the Scriptures, because what you see was foreseen, what you behold was foretold. Hear, daughter, see (Psalm 44); hear what was foretold, see what was fulfilled.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Luke.html"
source_title = "On the Gospel of Luke"


[[commentary]]
quote='''
When he was about to ascend into heaven, our Lord first took care to instruct his disciples diligently concerning the mystery of faith in him. They might therefore preach it with greater certainty to the world, because they had received it from the mouth of Truth himself and recognized that the words of the prophets had long ago foreshadowed it. He appeared to them after the triumph of his resurrection, according to what we heard just now when the Gospel was read. He said, “These are the words which I spoke to you when I was still with you.” That means, “When I still had a corruptible and mortal body like yours.” “Everything written about me in the law of Moses and the prophets and the psalms must be fulfilled.” He said that he fulfilled the mysteries which Moses, the prophets and the psalms proclaimed. It is perfectly evident that the church is one in all its saints and that the faith of all the chosen is the same, of those who preceded and who followed his coming in the flesh. We are saved through faith in his incarnation, passion and resurrection that have been accomplished.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bede%2FHomilies%2520on%2520the%2520Gospels.html'
source_title="Homilies on the Gospels 11.15"

[[commentary]]
quote='''
But after that He was seen, touched, and had eaten, lest He should seem to have mocked the human senses in any one respect, He had recourse to the Scriptures. And he said unto them, These are the words which I spake unto you, when I was yet with you, that is, when I was yet in the mortal flesh, in which ye also are. He indeed was then raised again in the same flesh, but was not in the same mortality with them. And He adds, That all things must be fulfilled which were written in the Law of Moses, and in the Prophets, and in the Psalms, concerning me.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%252024.html'
source_title='Catena Aurea by Aquinas'
