[[commentary]]
quote='''
According to these things will be the day when the Son of Man will be revealed. Beautifully He will be revealed, because He who now unseen sees everything, then seen will judge everything. However, He will appear to judge at the very time when He will see all forgotten of His judgments, given over to this world. For although the end of the world is set to come at a predetermined time, yet with the love of many growing cold towards the end, the iniquity of the human race will increase so much that it must deservedly be destroyed along with the world it inhabits. Even now we see countless people so devoted to revelry and drunkenness, buying and selling, and other worldly matters, that it’s clear they provoked the wrath of the strict judge, but we fear that worse things are yet to come, things which no wise person can even think about without grave sorrow. For what was once said about one sinful nation to be destroyed: The sin of the Amorites has not yet reached its full measure (Genesis 15), undoubtedly must be understood concerning the entire mass of the wicked to be condemned.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Luke.html"
source_title = "On the Gospel of Luke"


[[commentary]]
quote='''
For He who in the mean time though we see Him not yet sees all things, shall then appear to judge all things. And He shall come especially at that time, when He shall see all who are forgetful of His judgments in bondage to this world.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Luke%2FChapter%252017.html'
source_title='Catena Aurea by Aquinas'
