[[commentary]]
quote='''
(ubi sup.) Moreover, he doubted of the will of the Lord, not as disbelieving His compassion, but, as conscious of his own filth, he did not presume. It goes on; But Jesus, moved with compassion, put forth his hand, and touched him, and saith unto him, I will, be thou clean. It is not, as many of the Latins think, to be taken to mean and read, I wish to cleanse thee, but that Christ should say separately, I will, and then command, be thou clean.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Mark%2FChapter%25201.html'
source_title='Catena Aurea by Aquinas'

[[commentary]]
quote='''
(ubi sup.) Another reason why He touched him, was to prove that He could not be defiled, who freed others from pollution. At the same time it is remarkable, that He healed in the way in which He had been begged to heal. If thou will, says the leper, thou canst make me clean. I will, He answered, behold, thou hast My will, be clean; now thou hast at once the effect of My compassion.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Mark%2FChapter%25201.html'
source_title='Catena Aurea by Aquinas'

[[commentary]]
quote='''
(ubi sup.) But when the hand of the Saviour, that is, the Incarnate Word of God, is stretched out, and touches human nature, it is cleansed from the various parts of the old error.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Mark%2FChapter%25201.html'
source_title='Catena Aurea by Aquinas'
