[[commentary]]
quote='''
But watch yourselves, for they will deliver you up to councils, and you will be beaten in synagogues, and you will stand before kings and governors for my sake, for a testimony to them. Indeed, the very fact that the Jewish people, either alone or as the greatest cause, were the cause of their own destruction, because after the killing of the Lord Savior, they tormented the heralds and confessors of his name and faith with impious cruelty.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Mark.html"
source_title = "On the Gospel of Mark"

[[commentary]]
quote='''
(ubi sup.) The Lord shows how Jerusalem and the province of Judæa merited the infliction of such calamities, in the following words: But take heed to yourselves: for they shall deliver you up to councils; and in the synagogues ye shall be beaten. For the greatest cause of destruction to the Jewish people was, that after slaying the Saviour, they also tormented the heralds of His name and faith with wicked cruelty.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Mark%2FChapter%252013.html'
source_title='Catena Aurea by Aquinas'
