[[commentary]]
quote='''
But the Pharisees went out and immediately took counsel with the Herodians against him, how to destroy him. He refers to the Herodians as the ministers of Herod the tetrarch, who, on account of the enmity which their lord exercised against John, also plotted against and hated the Savior whom John preached. However, it was of great foolishness for those who greatly needed salvation to take counsel about the death of the Savior. Their zeal for wickedness is shown when they even consider it a crime that he stretched out the hand of the one who was sick to heal it at his word, as if none of them had ever done greater works on the Sabbath, such as carrying food, offering a cup, and performing other necessary tasks for sustenance. For indeed, he who said "Let there be," and it was made, could not be convicted of working on the Sabbath.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Mark.html"
source_title = "On the Gospel of Mark"


[[commentary]]
quote='''
(in Marc. i. 15) The Pharisees, thinking it a crime that at the word of the Lord the hand which was diseased was restored to a sound state, agreed to make a pretext of the words spoken by our Saviour; wherefore it is said, And the Pharisees went forth, and straightway took counsel with the Herodians against him, how they might destroy him. As if every one amongst them did not greater things on the sabbath day, carrying food, reaching forth a cup, and whatever else is necessary for meals. Neither could He, Who said and it was done, be convicted of toiling on the sabbath day.

(ubi sup.) Or else he calls Herodians the servants of Herod the Tetrarch, who on account of the hatred which their lord had for John, pursued with treachery and hate the Saviour also, Whom John preached.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Mark%2FChapter%25203.html'
source_title='Catena Aurea by Aquinas'
