[[commentary]]
quote='''
(ubi sup.) His oath does not excuse his murder, for perchance his reason for swearing was, that he might find an opportunity for slaying, and if she had demanded the death of his father and mother, he surely would not have granted it. It goes on, And she went forth, and said unto her mother, What shall I ask? And she said, The head of John the Baptist. Worthy is blood to be asked as the reward of such a deed as dancing. It goes on, And she came in straightway with haste, &c.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Mark%2FChapter%25206.html'
source_title='Catena Aurea by Aquinas'
