[[commentary]]
quote='''
(ubi sup.) Moreover, whilst the Lord is preaching in the house, there is not room for them, not even at the door, because whilst Christ is preaching in Judæa, the Gentiles are not yet able to enter to hear Him, to whom, however, though placed without, he directed the words of His doctrine by His preachers.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Mark%2FChapter%25202.html'
source_title='Catena Aurea by Aquinas'
