[[commentary]]
quote='''
The angel and Tobias went ahead to his parents; then his wife followed with substance and her family. After the divine grace, the illuminator, precedes to enlighten the blindness of the Jewish people, and they recognize in their writings that Christ is true God and man, and after the acknowledgment of the true faith, as if seeing the angel and their son whom they had not seen for a long time, rejoicing greatly; thus finally they join themselves to the holy Church, which is gathered from the Gentiles, in the participation of heavenly mysteries.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Tobit.html'
source_title="Commentary on Tobit"
