[[commentary]]
quote='''
Tobias, being brought into Sarah’s chamber, took out part of the liver from his bag, etc. And the Lord, about to receive the Church from the Gentiles, in the first beginning of its dispensation, commands that in each believer Satan and all his works, and all his pomps be renounced; and then to confess the faith of the Holy Trinity for the remission of sins, which is to burn the innermost bowels of peace with living coals.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Tobit.html'
source_title="Commentary on Tobit"
