[[commentary]]
quote='''
Hence, finally, Solomon is reported to have had several wives at once, to whom the Lord had said: "There has not been a wise man like you before you, and after you there shall not be." Because, therefore, the Lord had given him a multitude of prudence, "like the sand of the sea," that he might judge his people "in wisdom," therefore he was able to exercise several virtues at once.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Genesis%2FHomily11.html'
source_title="HOMILIES ON GENESIS 11.2"
