[[commentary]]
quote='''
"You have led forth this your people in your righteousness, whom you have set free. You have comforted them by your power in your holy rest." The Lord leads forth "in righteousness" his people whom "he set free through the laver of regeneration," and he comforts them also through the consolation of the Holy Spirit in "his power and in his rest." For the hope of things to come brings rest to those who labor; just as, for those set in the contest, the hope of the crown soothes the pain of wounds.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Exodus%2FHomily06.html'
source_title="HOMILIES ON EXODUS 6"
