[[commentary]]
quote='''
He sets forth therefore loaves sprinkled with "three measures of fine flour." He received three men, he sprinkled loaves with "three measures of fine flour." The whole of what he does is mystical, the whole is filled with sacraments.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Genesis%2FHomily04.html'
source_title="HOMILIES ON GENESIS 4.2"


[[commentary]]
quote='''
He says therefore to his wife Sarah: "Hasten to the tent, and sprinkle three measures of fine flour, and make loaves baked in the ashes." This in Greek is called ἐγχρυφίας, which indicates hidden or concealed loaves.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Genesis%2FHomily04.html'
source_title="HOMILIES ON GENESIS 4.1"
