[[commentary]]
quote='''
It does not seem to me that God promises this, that He will walk in the land of the Jews, but that, if anyone should deserve to be of so pure a heart as to be capable of God, in him God says that He "walks". — "And you shall be to me a people".
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Leviticus%2FHomily16.html'
source_title="HOMILIES ON LEVITICUS 16"
