[[commentary]]
quote='''
This he said at the suggestion and urgent persuasion of the Jews, who also watched us, as we sought to take him out of the fire, being ignorant of this, that it is neither possible for us ever to forsake Christ, who suffered for the salvation of such as shall be saved throughout the whole world (the blameless one for sinners), nor to worship any other. For Him indeed, as being the Son of God, we adore; but the martyrs, as disciples and followers of the Lord, we worthily love on account of their extraordinary affection towards their own King and Master, of whom may we also be made companions and fellow-disciples!
'''
source_url='https://historicalchristian.faith/by_father.php?file=Polycarp%2520of%2520Smyrna%2FMartyrdom%2520of%2520Polycarp.html'
source_title="MARTYRDOM OF POLYCARP 17"
