[[commentary]]
quote='''
Every faculty you have, your power of thinking or of moving your limbs from moment to moment, is given you by God. If you devoted every moment of your whole life exclusively to His service you could not give Him anything that was not in a sense His own already. So that when we talk of a man doing anything for God or giving anything to God, I will tell you what it is really like. It is like a small child going to its father and saying, 'Daddy, give me sixpence to buy you a birthday present.' Of course, the father does, and he is pleased with the child's present. It is all very nice and proper, but only an idiot would think that the father is sixpence to the good on the transaction. When a man has made these two discoveries God can really get to work. It is after this that real life begins.
'''
source_url=''
source_title='Mere Christianity, Book 3, Chapter 11: Faith'

[[commentary]]
quote='''
It is when Dick realises that his niceness is not his own but a gift from God, and when he offers it back to God—it is just then that it begins to be really his own. For now Dick is beginning to take a share in his own creation. The only things we can keep are the things we freely give to God. What we try to keep for ourselves is just what we are sure to lose.
'''
source_url=''
source_title='Mere Christianity, Book 4, Chapter 10: Nice People or New Men'
