[[commentary]]
quote='''
God's own nature is the real sanction of His commands, yet to understand this must, in the end, lead us to the conclusion that union with that Nature is bliss and separation from it horror. Thus Heaven and Hell come in. But it may well be that to think much of either except in this context of thought, to hypostatise them as if they had a substantial meaning apart from the presence or absence of God, corrupts the doctrine of both and corrupts us while we so think of them.
'''
source_url=''
source_title='Surprised by Joy, Ch. 15: The Beginning'
