[[commentary]]
quote='''
The work of a Beethoven, and the work of a charwoman, become spiritual on precisely the same condition, that of being offered to God, of being done humbly "as to the Lord". This does not, of course, mean that it is for anyone a mere toss-up whether he should sweep rooms or compose symphonies. A mole must dig to the glory of God and a cock must crow. We are members of one body, but differentiated members, each with his own vocation.
'''
source_url=''
source_title='Learning in War-Time, from The Weight of Glory'
