[[commentary]]
quote='''
Obviously you are making excellent progress. My only fear is lest in attempting to hurry the patient you awaken him to a sense of his real position. For you and I, who see that position as it really is, must never forget how totally different it ought to appear to him. We know that we have introduced a change of direction in his course which is already carrying him out of his orbit around the Enemy; but he must be made to imagine that all the choices which have effected this change of course are trivial and revocable. He must not be allowed to suspect that he is now, however slowly, heading right away from the sun on a line which will carry him into the cold and dark of utmost space.
'''
append_to_author_name=' (via the character Screwtape, a devil)'
source_url=''
source_title='The Screwtape Letters, Chapter XII'

[[commentary]]
quote='''
The first step is to recognise the fact that your moods change. The next is to make sure that, if you have once accepted Christianity, then some of its main doctrines shall be deliberately held before your mind for some time every day. That is why daily prayers and religious readings and church-going are necessary parts of the Christian life. We have to be continually reminded of what we believe. Neither this belief nor any other will automatically remain alive in the mind. It must be fed. And as a matter of fact, if you examined a hundred people who had lost their faith in Christianity, I wonder how many of them would turn out to have been reasoned out of it by honest argument? Do not most people simply drift away?
'''
source_url=''
source_title='Mere Christianity, Book 3, Chapter 11: Faith'
