[[commentary]]
quote='''
Chastity is the most unpopular of the Christian virtues. There is no getting away from it; the Christian rule is, "Either marriage, with complete faithfulness to your partner, or else total abstinence." Now this is so difficult and so contrary to our instincts, that obviously either Christianity is wrong or our sexual instinct, as it now is, has gone wrong. One or the other. Of course, being a Christian, I think it is the instinct which has gone wrong.
'''
source_url=''
source_title='Mere Christianity, Book 3, Chapter 5: Sexual Morality'
