[[commentary]]
quote='''
Obviously you are making excellent progress. My only fear is lest in attempting to hurry the patient you awaken him to a sense of his real position. For you and I, who see that position as it really is, must never forget how totally different it ought to appear to him. We know that we have introduced a change of direction in his course which is already carrying him out of his orbit around the Enemy; but he must be made to imagine that all the choices which have effected this change of course are trivial and revocable. He must not be allowed to suspect that he is now, however slowly, heading right away from the sun on a line which will carry him into the cold and dark of utmost space.
'''
append_to_author_name=' (via the character Screwtape, a devil)'
source_url=''
source_title='The Screwtape Letters, Chapter XII'
