[[commentary]]
quote='''
According to Christian teachers, the essential vice, the utmost evil, is Pride. Unchastity, anger, greed, drunkenness, and all that, are mere fleabites in comparison: it was through Pride that the devil became the devil: Pride leads to every other vice: it is the complete anti-God state of mind...

Pride gets no pleasure out of having something, only out of having more of it than the next man. We say that people are proud of being rich, or clever, or good-looking, but they are not. They are proud of being richer, or cleverer, or better-looking than others. If everyone else became equally rich, or clever, or good-looking there would be nothing to be proud about. It is the comparison that makes you proud: the pleasure of being above the rest...

But pride always mean enmity - it is enmity. And not only enmity between man and man, but enmity to God. In God you come up against something which is in every respect immeasurably superior to yourself. Unless you know God as that - and therefore, know yourself as nothing in comparison - you do not know God at all. As long as you are proud you cannot know God. A proud man is always looking down on things and people: and, of course, as long as you are looking down, you cannot see something that is above you.
'''
source_url=''
source_title='Mere Christianity, The Great Sin'

[[commentary]]
quote='''
Good and evil, then, are not on all fours. Badness is not even bad in the same way in which goodness is good. Ormuzd and Ahriman cannot be equals. In the long run, Ormuzd must be original and Ahriman derivative. The first hazy idea of devil must, if we begin to think, be analysed into the more precise ideas of 'fallen' and 'rebel' angel.
'''
source_url=''
source_title='Evil and God, from God in the Dock'

[[commentary]]
quote='''
Now it is impossible at this point not to remember a certain sacred story which, though never included in the creeds, has been widely believed in the Church and seems to be implied in several Dominical, Pauline, and Johannine utterances--I mean the story that man was not the first creature to rebel against the Creator, but that some older and mightier being long since became apostate and is now the emperor of darkness and (significantly) the Lord of this world.
'''
source_url=''
source_title='The Problem of Pain, Chapter 9: Animal Pain'

[[commentary]]
quote='''
It seems to me, therefore, a reasonable supposition, that some mighty created power had already been at work for ill on the material universe, or the solar system, or, at least, the planet Earth, before ever man came on the scene: and that when man fell, someone had, indeed, tempted him. This hypothesis is not introduced as a general "explanation of evil": it only gives a wider application to the principle that evil comes from the abuse of free-will. If there is such a power, as I myself believe, it may well have corrupted the animal creation before man appeared.
'''
source_url=''
source_title='The Problem of Pain, Chapter 9: Animal Pain'

[[commentary]]
quote='''
And do you now begin to see why Christianity has always said that the devil is a fallen angel? That is not a mere story for the children. It is a real recognition of the fact that evil is a parasite, not an original thing. The powers which enable evil to carry on are powers given it by goodness. All the things which enable a bad man to be effectively bad are in themselves good things—resolution, cleverness, good looks, existence itself. That is why Dualism, in a strict sense, will not work.
'''
source_url=''
source_title='Mere Christianity, The Invasion'

[[commentary]]
quote='''
When we have understood about free will, we shall see how silly it is to ask, as somebody once asked me: 'Why did God make a creature of such rotten stuff that it went wrong?' The better stuff a creature is made of—the cleverer and stronger and freer it is—then the better it will be if it goes right, but also the worse it will be if it goes wrong. A cow cannot be very good or very bad; a dog can be both better and worse; a child better and worse still; an ordinary man, still more so; a man of genius, still more so; a superhuman spirit best—or worst—of all.

How did the Dark Power go wrong? Here, no doubt, we ask a question to which human beings cannot give an answer with any certainty. A reasonable (and traditional) guess, based on our own experiences of going wrong, can, however, be offered. The moment you have a self at all, there is a possibility of putting yourself first—wanting to be the centre—wanting to be God, in fact. That was the sin of Satan: and that was the sin he taught the human race.
'''
source_url=''
source_title='Mere Christianity, Book 2, Chapter 3: The Shocking Alternative'

[[commentary]]
quote='''
If you mistake for your own merits what are really God's gifts to you through nature, and if you are contented with simply being nice, you are still a rebel: and all those gifts will only make your fall more terrible, your corruption more complicated, your bad example more disastrous. The Devil was an archangel once; his natural gifts were as far above yours as yours are above those of a chimpanzee.
'''
source_url=''
source_title='Mere Christianity, Book 4, Chapter 10: Nice People or New Men'
