[[commentary]]
quote='''
They know that the Lord (not merely obedience to the Lord) is 'righteous' and commands 'righteousness' because He loves it. He enjoins what is good because it is good, because He is good. Hence His laws have emeth 'truth', intrinsic validity, rock-bottom reality, being rooted in His own nature, and are therefore as solid as that Nature which He has created. But the Psalmists themselves can say it best; 'thy righteousness standeth like the strong mountains; thy judgements are like the great deep' (36:6). Their delight in the Law is a delight in having touched firmness; like the pedestrian's delight in feeling the hard road beneath his feet after a false short cut has long entangled him in muddy fields.
'''
source_url=''
source_title='Reflections on the Psalms, Chapter VI: Sweeter Than Honey'
