[[commentary]]
quote='''
And he will not be weary or faint. He will not slumber or sleep, nor will his waist belt be loosened or his sandal strap be broken. The divine word describes the speed of the approaching army, which came not by its own will, but by the will of the Lord; indeed, it was drawn in and provoked by its hiss, which did not fail or tire from such a journey, and did not allow sleep to its eyes, and whose sandals were not worn out.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
