[[commentary]]
quote='''
And according to the Septuagint, 'to carry away the seed of the Chaldeans' is referred to the person of the Lord: the one who is truly loved by the Father, and who does all the will of the Father, and who overturns in Babylon, that is, in the confusion of this world, all the seed of the Chaldeans, which are interpreted as demons. He himself spoke and heard the Son, and brought him, who speaks to the believers: Come to me, all you who labor and are burdened.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FCommentary%2520on%2520Isaiah.html'
source_title="Commentary on Isaiah"
