[[commentary]]
quote='''
(Verse 24) And those who wander in spirit will gain understanding, and murmurers will learn the Law. (LXX: And those who wander in spirit will gain understanding, and murmurers will learn obedience, and those with stammering tongues will learn to speak peace.)

And then those who now wander in spirit will understand the knowledge of God, and those who once murmured against the Lord in the wilderness will learn the Law, of which they previously had no knowledge. For if they had received Moses, they would have also received the Lord Jesus Christ, because Moses spoke of him.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FCommentary%2520on%2520Isaiah.html'
source_title='Commentary on Isaiah'
