[[commentary]]
quote='''
(V. 2.) The names of the twelve apostles are as follows. The catalog of apostles is provided in order to exclude those who will be false apostles.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FCommentary%2520on%2520Matthew.html'
source_title="Commentary on Matthew"


[[commentary]]
quote='''
(Verse 3.) The first is Simon, who is called Peter, and Andrew his brother; James the son of Zebedee, and John his brother; Philip and Bartholomew; Thomas, and Matthew the tax collector; James the son of Alphaeus, and Thaddaeus. The order and merit of each apostle was determined by the one who searches the secrets of the heart. The first is written Simon, with the surname Peter, to distinguish him from the other Simon who is called the Cananaean, from the village of Cana in Galilee, where the Lord turned water into wine (John 2). He also calls James the son of Zebedee, because another James follows, James the son of Alphaeus. And he pairs the apostles together. He joins Peter and Andrew as brothers, not so much in flesh as in spirit. He also joins James and John, who, leaving behind the bread of the body, followed the true Father. He pairs Philip and Bartholomew, and also Thomas and Matthew the tax collector. The other evangelists, in the order of names, first mention Matthew; and afterwards Thomas, they do not mention the name of the tax collector, so as not to appear to criticize the evangelist while recalling the early way of life. But indeed, (as we said above), he places himself after Thomas and calls himself a publican, so that where sin abounded, grace may abound even more (Rom. V, 20).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FCommentary%2520on%2520Matthew.html'
source_title="Commentary on Matthew"


[[commentary]]
quote='''
A catalogue of the names of the Apostles is given, that all false Apostles might be excluded. The names of the twelve Apostles are these; First, Simon who is called Peter, and Andrew his brother. To arrange them in order according to their merit is His alone who searches the secrets of all hearts. But Simon is placed first, having the surname of Peter given to distinguish him from the other Simon surnamed Chananæus, from the village of Chana in Galilee where the Lord turned the water into wine.

The Evangelist couples the names throughout in pairs. So he puts together Peter and Andrew, brothers not so much according to the flesh as in spirit; James and John who left their father after the flesh to follow their true Father; James the son of Zebedee and John his brother. He calls him the son of Zebedee, to distinguish him from the other James the son of Alphæus.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Matthew%2FChapter%252010.html'
source_title="Catena Aurea by Aquinas"
