[[commentary]]
quote='''
(Verse 17) And Jesus rebuked him, and the demon came out of him, and the boy was healed from that hour. It was not the boy who suffered, but rather the demon who ought to be rebuked. Whether he rebuked the boy, and the demon came out of him: because he had been oppressed by the demon due to his own sins.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FCommentary%2520on%2520Matthew.html'
source_title='Commentary on Matthew'

[[commentary]]
quote='''
Not that we must think that He was overcome by weariness of them, and that The meek and gentle broke out into words of wrath, but as a physician who might see the sick man acting against his injunctions, would say, How long shall I frequent your chamber? How long throw away the exercise of my skill, while I prescribe one thing, and you do another? That it is the sin, and not the man with whom He is angry, and that in the person of this one man He convicts the Jews of unbelief, is clear from what He adds, Bring him to me.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Matthew%2FChapter%252017.html'
source_title="Catena Aurea by Aquinas"
