[[commentary]]
quote='''
(Ver. 18.) And Jesus came to them and spoke, saying: All power has been given to me in heaven and on earth. The power was given to him who was recently crucified, who was buried in a tomb, who had been dead, and who later rose again. Power has been given in heaven and on earth, so that he who previously reigned in heaven may now reign on earth through the faith of believers.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FCommentary%2520on%2520Matthew.html'
source_title='Commentary on Matthew'

[[commentary]]
quote='''
Power is given to Him, Who but a little before was crucified, Who was buried, but Who afterwards rose again.

Power is given in heaven and in earth, that He who before reigned in heaven, should now reign on earth by the faith of the believers.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Matthew%2FChapter%252028.html'
source_title="Catena Aurea by Aquinas"

[[commentary]]
quote='''
“Jesus approached them and said, ‘All authority in heaven and earth has been given to me.’ ” This authority was given to one who had just been crucified, buried in a tomb, laid dead and afterwards had arisen. Authority was given to him in both heaven and earth so that he who once reigned in heaven might also reign on earth through the faith of his believers.
'''
source_url=''
source_title="COMMENTARY ON MATTHEW 4.28.18-20"
