[[commentary]]
quote='''
The young lions roaring, that they may seize, and seek from God their food. He said fittingly, from God: since indeed he desires to deceive the saints — for example, Judas, David, Solomon, Peter — as it is written: "His food is choice."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FHomilies%2520on%2520Psalms%2Fhomily_030.html'
source_title="Homily 30, on Psalm 103"
