[[commentary]]
quote='''
"He split the sea and led them through." The Lord walked upon the sea, and calmed the waves of the sea, and led us through. "He split the sea and led them through." To this day, O faithful monk, when you are led out of Egypt, the sea is split, and thus you are led out. "He set the waters as if in a wineskin." In the Hebrew it does not have "wineskin," but "heap."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FHomilies%2520on%2520Psalms%2Fhomily_011.html'
source_title="Homily 11, on Psalm 77"
