[[commentary]]
quote='''
Confess to the Lord and call upon his name. Confess and say: because we are sinners, but you are merciful, and you have mercy on us. And call upon his name. So that we may not fashion idols in our hearts, but we will call upon our Lord, and he himself will be our redemption. Proclaim his works among the nations. Let the Jews blush, who say that only within Israel were his wonders and his works accomplished.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FHomilies%2520on%2520Psalms%2Fhomily_031.html'
source_title="Homily 31, on Psalm 104"
