[[commentary]]
quote='''
The Lord keeps the little ones. If anyone is great, and exalts himself, and is proud, this man the Lord does not keep; if anyone thinks himself great, on this man the Lord has no mercy: but if anyone humbles himself, on this man the Lord has mercy, and the Lord keeps him. Since he says: "Behold, I and the children whom the Lord has given me." And again: I was humbled, and he saved me. We understand "I was humbled, and he saved me" in two ways: either I sinned, and he saved me; or, when I was proud, he humbled me and saved me.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FHomilies%2520on%2520Psalms%2Fhomily_039.html'
source_title="Homily 39, on Psalm 114"
