[[commentary]]
quote='''
You have remitted the iniquity of Your people. Not on account of their works, but on account of Your mercy, You have saved Your people. You have covered all their sins.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FHomilies%2520on%2520Psalms%2Fhomily_017.html'
source_title="Homily 17, on Psalm 84"


[[commentary]]
quote='''
You have remitted the iniquity of Your people. No one remits anything except what is owed. You have covered all their sins. You have covered them with virtues, and therefore the sins do not appear. For example, You have covered iniquity with righteousness, You have covered unchastity with chastity, You have covered blackness with whiteness.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FHomilies%2520on%2520Psalms%2Fhomily_017.html'
source_title="Homily 17, on Psalm 84"


[[commentary]]
quote='''
You have forgiven the iniquity of your people. This we believe was accomplished in baptism. You have covered all their sins. This in penance, as is said in the thirty-first psalm: "Blessed are they whose iniquities are forgiven, and whose sins are covered." In baptism our iniquities are forgiven us, but in penance the sins that had been committed are covered over: they are not dismissed, but covered over. Let us carefully consider the force of the word. For when the Lord and Savior comes, all our iniquities are utterly forgiven us in baptism. For when we were living without law, we were sinning without law — ἀνομία it is called in Greek, that is, sin without law; but when we have received baptism, it is by no means called ἀνομία, but sin is called sin. For sin is not imputed except to him who knows it to be sin: where there is transgression of a commandment, there is true sin. Do you wish to know how sins are covered over by virtues? Yesterday I was dissolute, today I am chaste: chastity covers over lust. Yesterday I was imprudent, today I am prudent, I repent of my error: prudence covers over imprudence. Yesterday I was seizing what belonged to others, today I distribute what is my own: almsgiving covers over greed. Blessed is he whose iniquities are forgiven in baptism: but the second is penance, which is like a plank after shipwreck. Therefore that man too can be called blessed: though he be delivered amid peril, yet because he is delivered in penance, he is to be called blessed.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FHomilies%2520on%2520Psalms%2Fhomily_064.html'
source_title="Homily 64, on Psalm 84 (Alternate Series)"
