[[commentary]]
quote='''
So the unfortunate man, who cannot tolerate the woman he has chosen from all the women in the world, is not encouraged to return to her and tolerate her, but encouraged to choose another woman whom he may in due course refuse to tolerate. And in all these cases the argument is the same; that the man in the intermediate state is unhappy. Probably he is unhappy, since he is abnormal; but the point is that he is permitted to loosen the universal bond which has kept millions of others normal. Because he has himself got into a hole, he is allowed to burrow in it like a rabbit and undermine a whole countryside.
'''
source_url=''
source_title='The Superstition of Divorce, Ch. 4'
