[[commentary]]
quote = '''
If ever a man on this earth lived to embody the tremendous text, "But if the \
light in your body be darkness, how great is the darkness," it was certainly he. \
Great men like Ariosto, Rabelais, and Shakspere fall in foul places, flounder in \
violent but venial sin, sprawl for pages, exposing their gigantic weakness, are \
dirty, are indefensible; and then they struggle up again and can still speak with \
a convincing kindness and an unbroken honour of the best things in the world: \
Rabelais, of the instruction of ardent and austere youth; Ariosto, of holy \
chivalry; Shakspere, of the splendid stillness of mercy. But in Zola even the \
ideals are undesirable; Zola's mercy is colder than justice—nay, Zola's mercy \
is more bitter in the mouth than injustice. When Zola shows us an ideal training \
he does not take us, like Rabelais, into the happy fields of humanist learning. \
He takes us into the schools of inhumanist learning, where there are neither \
books nor flowers, nor wine nor wisdom, but only deformities in glass bottles, \
and where the rule is taught from the exceptions. Zola's truth answers the exact \
description of the skeleton in the cupboard; that is, it is something of which a \
domestic custom forbids the discovery, but which is quite dead, even when it is \
discovered. Macaulay said that the Puritans hated bear-baiting, not because it \
gave pain to the bear, but because it gave pleasure to the spectators. Of such \
substance also was this Puritan who had lost his God. A Puritan of this type is \
worse than the Puritan who hates pleasure because there is evil in it. This man \
actually hates evil because there is pleasure in it. Zola was worse than a \
pornographer, he was a pessimist. He did worse than encourage sin: he encouraged \
discouragement. He made lust loathsome because to him lust meant life.
'''
source_title = "The Zola Controversy"
source_url = ""
