[[commentary]]
quote='''
"Remember always that there is one thing that cannot be endured by anybody or anything. That one unendurable thing is to be overworked and also neglected. ...But no beast of the field, no horse, no dog can endure long to be asked to do more than his work and yet have less than his honour."
'''
source_url=''
source_title='Tremendous Trifles, A Somewhat Improbable Story (1909)'
