[[commentary]]
quote='''
Nor do groanings alone commend the turtledove; chastity also commends it. By the merit of this chastity indeed it was worthy to be given as an offering for the virginal birth. For so you have it: "A pair of turtledoves, or two young pigeons" (Lk 2:24). And although elsewhere indeed the Holy Spirit is usually designated by a dove; yet because it is a lustful bird, it was not fitting that it be offered in sacrifice to the Lord, except at that age when it would not know lust. But no age is specified for the turtledove, because its chastity is recognized at every age.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bernard%2520of%2520Clairvaux%2FSermons%2520on%2520the%2520Song%2520of%2520Songs%2FSermon%252059.html'
source_title="Sermons on the Song of Songs, Sermon 59"
