[[commentary]]
quote='''
So it is necessary that you also receive in this way the command that you love your neighbor as yourself (Mt 22:39), even if it is not so openly expressed. Or do you not finally judge it sufficient for fulfilling this commandment concerning love of neighbor, if you perfectly observe that which is rightly prescribed to every man by the law of nature: "What you do not wish done to you, do not do to another"? (Tob 4:16.) And likewise: "Whatever you wish that men should do to you, do also to them" (Mt 7:12).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bernard%2520of%2520Clairvaux%2FSermons%2520on%2520the%2520Song%2520of%2520Songs%2FSermon%252050.html'
source_title="Sermons on the Song of Songs, Sermon 50"
