[[commentary]]
quote='''
God is Wisdom, and he wills to be loved not only sweetly but also wisely. Whence the Apostle says: "Let your worship be rational." Otherwise the spirit of error will most easily deceive your zeal, if you neglect knowledge; nor does the cunning enemy have a more effective device for removing love from the heart than if he can bring it about that one walks in it carelessly and not with reason.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bernard%2520of%2520Clairvaux%2FSermons%2520on%2520the%2520Song%2520of%2520Songs%2FSermon%252019.html'
source_title="Sermons on the Song of Songs, Sermon 19"
