[[commentary]]
quote='''
They cry out Hosanna, that is save us, that men might be saved by Him who was blessed, and was a conqueror and came in the name of the Lord, that is, of His Father, since the Father is so called because of the Son, and the Son, because of the Father.

Or Hosanna, that is, save in the highest as well as in the lowest, that is, that the just be built on the ruin of Angels, and also that both those on the earth and those under the earth should be saved. In a mystical sense, also, the Lord approaches Jerusalem, which is 'the vision of peace,' in which happiness remains fixed and unmoved, being, as the Apostle says, the mother of all believers. (Gal. 4:26)

Those who went before are the prophets, and those who followed are the Apostles.
'''
time=1274
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Mark%2FChapter%252011.html'
source_title='Catena Aurea by Aquinas'
