[[commentary]]
quote='''
...blessed then will he be, and truly proclaimed perfect, "that the excellency of the power may be of God, and not of us," as the apostle says. Only let us preserve free-will and love: "troubled on every side, yet not distressed; perplexed, but not in despair; persecuted, but not forsaken; cast down, but not destroyed." For those who strive after perfection, according to the same apostle, must "give no offence in anything, but in everything approve themselves not to men, but to God."
'''
source_url="https://historicalchristian.faith/by_father.php?file=Clement%2520of%2520Alexandria%2FThe%2520Stromata%2520Book%25204.html"
source_title="The Stromata Book 4"
