[[commentary]]
quote='''
Through the promised inheritance, which they did not receive, it became evident that “they looked forward to the city which has foundations, whose builder and maker is God.”
'''
source_url=''
source_title="COMMENTARY ON THE EPISTLE TO THE HEBREWS"
