[[commentary]]
quote='''
"But now I go my way to Him that sent me; and none of you," He says, "asketh me, Whither goest Thou?" He means that His departure would be such that none would ask Him of that which they should see taking place in broad daylight before their eyes: for previously to this they had asked Him whither He was going, and had been answered that He was going whither they themselves could not then come. Now, however, He promises that He will go away in such a manner that none of them shall ask Him whither He goes. For a cloud received Him when He ascended up from their side; and of His going into heaven they made no verbal inquiry, but had ocular evidence.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Augustine%2520of%2520Hippo%2FTRACTATES%2520ON%2520JOHN%2FTractate%252094.html'
source_title='Tractates on John 94'

[[commentary]]
quote='''
(Tr. xciv) Or whereas they had asked Him above, whither He was going, and He had replied that He was going whither they would not come; now He promises that He will go in such a way that no one will ask Him whither He goeth: and none of you asketh Me, Whither goest Thou? Going up to heaven, they questioned Him not in words, but followed with their eyes.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520John%2FChapter%252016.html'
source_title='Catena Aurea by Aquinas'
