[[commentary]]
quote='''
"O that," he saith, "my ways were made so direct, that I might keep Thy statutes" (ver. 5). Thou indeed hast charged: O that I could realize what thou hast charged. When thou hearest, "O that," recognise the words of one wishing; and having recognised the expression of a wish, lay aside the pride of presumption. For who saith that he desireth what he hath in such a manner in his power, that without need of any help he can do it? Therefore if man desireth what God chargeth, God must be prayed to grant Himself what He enjoineth...
'''
source_url='https://historicalchristian.faith/by_father.php?file=Augustine%2520of%2520Hippo%2FON%2520THE%2520PSALMS%2FPsalm%2520119.html'
source_title="Exposition on Psalm 119"
