[[commentary]]
quote='''
"I have found David My servant:" that David from David's seed: "with My holy oil have I anointed Him" (ver. 20): for it is said of Him, "God, even Thy God, hath anointed Thee with the oil of gladness above Thy fellows."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Augustine%2520of%2520Hippo%2FON%2520THE%2520PSALMS%2FPsalm%252089.html'
source_title="Exposition on Psalm 89"
