[[commentary]]
quote='''
We ought then to restrain every movement of anger and moderate it under the direction of discretion, that we may not by blind rage be hurried into that which is condemned by Solomon: "The wicked man expends all his anger, but the wise man dispenses it bit by bit," i.e., a fool is inflamed by the passion of his anger to avenge himself; but a wise man, by the ripeness of his counsel and moderation little by little diminishes it, and gets rid of it.
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Cassian%2FConferences%2520of%2520John%2520Cassian%2520-%2520Part%2520II%2F16.%2520The%2520First%2520Conference%2520of%2520Abbot%2520Joseph.html'
source_title="The First Conference of Abbot Joseph, Chapter 27"
